---
- name: MAIN - systemctl restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true

- name: MAIN - systemctl restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  become: true

- name: MAIN - reboot
  linode_state:
    token: "{{ secrets.external.linode.token }}"
    label_prefix: "{{ lab.domain | regex_replace('.com$', '') }}-portal"
    state: restarted
  delegate_to: localhost

- name: MAIN - waiting on host
  ansible.builtin.wait_for_connection:
