---
- name: MAIN - systemctl restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true

- name: MAIN - systemctl restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  become: true

- name: MAIN - systemctl restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  become: true

- name: MAIN - reboot
  ansible.builtin.reboot:
  become: true
