---
vault:
  persisted_host: docker00

  mount_point: lab/kv
  ipv4: "192.168.40.1"

  secret_paths:
    - certificates/expressvpn
    - external/linode
    - external/maxmind
    - containers/deluge
    - containers/elasticsearch/users/elastic
    - containers/elasticsearch/users/kibana_system
    - containers/expressvpn/users/admin
    - containers/gitlab/users/admin
    - containers/gitlab/runner
    - containers/gitlab/smtp
    - containers/kibana/encryption_keys
    - containers/nexus/users/admin
    - containers/oauth
    - containers/plex
    - containers/redis
    - containers/vault
    - containers/zoneminder/smtp
    - users/host/super/docker/00
    - users/host/super/docker/01
    - users/host/super/docker/02
    - users/host/super/portal
    - users/host/admin/docker/00
    - users/host/admin/docker/01
    - users/host/admin/docker/02
    - users/host/admin/portal
    - users/host/iac/docker/00
    - users/host/iac/docker/01
    - users/host/iac/docker/02
    - users/host/iac/nas
    - users/host/iac/portal
    - users/host/engineer/docker/00
    - users/host/engineer/docker/01
    - users/host/engineer/docker/02
    - users/host/engineer/portal
    - users/host/associate/docker/00
    - users/host/associate/docker/01
    - users/host/associate/docker/02
    - users/host/associate/portal
    - users/raid/red_ro
    - users/raid/blue_ro
    - users/raid/green_rw
    - users/raid/black_rw
