---
- name: MAIN - include groups tasks
  ansible.builtin.include_tasks: groups.yml
  no_log: true
  with_items:
    - "{{ entities.groups }}"

- name: MAIN - include users tasks
  ansible.builtin.include_tasks: users.yml
  no_log: true
  with_items:
    - "{{ entities.users }}"
