server {
    server_name                ping.home.elysianskies.com;
    listen                     443 ssl;
    ssl_certificate            /etc/nginx/nginx.crt;
    ssl_certificate_key        /etc/nginx/nginx.crt.key;
    proxy_set_header Host      $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Portal  true;

    location / {
        return 200 '{"proxy": "external", "response": "pong"}\n';

        add_header Content-Type application/json;
    }
}

server {
    server_name                home.elysianskies.com *.home.elysianskies.com;
    listen                     443 ssl;
    ssl_certificate            /etc/nginx/nginx.crt;
    ssl_certificate_key        /etc/nginx/nginx.crt.key;
    proxy_set_header Host      $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Portal  true;

    location / {
        proxy_pass https://127.0.0.1:{{ external_ports.nginx_web }};
    }
}

server {
    server_name                nas.home.elysianskies.com;
    listen                     443 ssl;
    ssl_certificate            /etc/nginx/nginx.crt;
    ssl_certificate_key        /etc/nginx/nginx.crt.key;
    proxy_http_version         1.1;
    proxy_set_header           Upgrade    $http_upgrade;
    proxy_set_header           Connection $http_connection;
    proxy_set_header Host      $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Portal  true;

    location / {
        proxy_pass https://127.0.0.1:{{ external_ports.nginx_web }};
    }
}
