---
- name: APT - include mirrors tasks
  ansible.builtin.include_tasks: mirrors.yml
  vars:
    apt_host: "{{ apt_object.mirror_proxy if discovered_nexus.status == 200 else apt_object.mirror_original }}"
  when: ansible_system_vendor != "Linode"

- name: APT - install additional packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: true
  become: true
  when: cycle_mode.name == "up"
  with_items:
    - "{{ ubuntu.additional_packages }}"
