---
- name: apt - create nexus auth file
  copy:
    dest: /etc/apt/auth.conf.d/elysianskies_nexus.conf
    content: |
      machine https://nexus.{{ assignments.nginx.networking.teine.fqdn }}
      login {{ secrets.nexus.username }}
      password {{ secrets.nexus.password }}
    owner: root
    group: root
    mode: '0600'
  become: true

- name: apt - override /etc/apt/sources.list
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }} main restricted
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }}-updates main restricted
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }} universe
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }}-updates universe
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }} multiverse
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }}-updates multiverse
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }}-backports main restricted universe multiverse
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }}-security main restricted
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }}-security universe
      deb https://nexus.{{ assignments.nginx.networking.teine.fqdn }}/repository/{{ ubuntu.apt.proxy }}/ {{ ubuntu.apt.distro }}-security multiverse
    owner: root
    group: root
    mode: '0644'
  become: true
