---
- name: HOSTS - configure local resolutions
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  with_items:
    - "{{ docker_hosts.host_1.networking.talamh.ipv4 }}    {{ docker_hosts.host_1.networking.talamh.fqdn }}"
    - "{{ docker_hosts.host_1.networking.uisge.ipv4 }}    {{ docker_hosts.host_1.networking.uisge.fqdn }}"
    - "{{ docker_hosts.host_1.networking.teine.ipv4 }}    {{ docker_hosts.host_1.networking.teine.fqdn }}"
    - "{{ docker_hosts.host_2.networking.talamh.ipv4 }}    {{ docker_hosts.host_2.networking.talamh.fqdn }}"
    - "{{ docker_hosts.host_2.networking.uisge.ipv4 }}    {{ docker_hosts.host_2.networking.uisge.fqdn }}"
