---
- name: MAIN - include hosts tasks
  ansible.builtin.include_tasks: hosts.yml
  when: ansible_system_vendor != "Linode"

- name: MAIN - include proxy tasks
  ansible.builtin.include_tasks: proxy.yml
  when: ansible_system_vendor != "Linode"

- name: MAIN - include arch tasks
  ansible.builtin.include_tasks: arch.yml

- name: MAIN - include pip tasks
  ansible.builtin.include_tasks: pip.yml
  when: cycle_mode.name == "up"

- name: MAIN - configure user sudoers
  ansible.builtin.copy:
    content: |
      {{ ansible_user }}    ALL=(ALL) NOPASSWD: ALL
    dest: "/etc/sudoers.d/{{ ansible_user }}"
    owner: root
    group: root
    mode: '0750'
  become: true
