---
- name: MAIN - include hosts tasks
  ansible.builtin.include_tasks: hosts.yml
  when: ansible_system_vendor != "Linode"

- name: MAIN - discover nexus apt repository
  ansible.builtin.uri:
    url: "{{ ubuntu.apt.mirror_proxy }}"
    status_code:
      - -1
      - 401
  register: discovered_nexus
  when: ansible_system_vendor != "Linode"

- name: MAIN - include apt tasks
  ansible.builtin.include_tasks: apt.yml
  vars:
    apt_host: "{{ ubuntu.apt.mirror_proxy if discovered_nexus.status == 401 else ubuntu.apt.mirror_original }}"
  when: ansible_system_vendor != "Linode"

- name: MAIN - install additional packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: true
  become: true
  with_items:
    - "{{ ubuntu.additional_packages }}"

- name: MAIN - include pip tasks
  ansible.builtin.include_tasks: pip.yml

- name: MAIN - configure user sudoers
  ansible.builtin.copy:
    content: |
      {{ ansible_user }}    ALL=(ALL) NOPASSWD: ALL
    dest: "/etc/sudoers.d/{{ ansible_user }}"
    owner: root
    group: root
    mode: '0750'
  become: true

- name: MAIN - include gateway tasks
  ansible.builtin.include_tasks: gateway.yml
  when: ansible_system_vendor != "Linode"

- name: MAIN - include wol tasks
  ansible.builtin.include_tasks: wol.yml
  vars:
    wol_interface: "{{ gateway.internal_interface }}"
  when: ansible_system_vendor != "Linode"
