---
- name: MAIN - configure user sudoers
  ansible.builtin.template:
    src: sudoers
    dest: /etc/sudoers.d/lab_sudoers
    owner: root
    group: root
    mode: '0600'
  become: true

- name: MAIN - include lab tasks
  ansible.builtin.include_tasks: lab.yml
  when: ansible_system_vendor != "Linode"

- name: MAIN - install general packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: true
  when: internet_found == "yes"
  become: true
  with_items:
    - "{{ ubuntu.general_packages }}"

- name: MAIN - install python packages
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  when: internet_found == "yes"
  become: true
  with_items:
    - "{{ ubuntu.python_packages }}"
