---
- name: PROXY - discover nexus apt repository
  ansible.builtin.uri:
    url: "{{ nexus_proxy }}"
    status_code:
      - 200
      - -1
  register: discovered_nexus

- name: PROXY - create nexus auth file
  ansible.builtin.copy:
    dest: /etc/apt/auth.conf.d/elysianskies_nexus.conf
    content: |
      machine https://nexus.{{ assignments.nginx.networking.teine.fqdn }}
      login {{ secrets.nexus.username }}
      password {{ secrets.nexus.password }}
    owner: root
    group: root
    mode: '0600'
  become: true
