---
- name: PROXY - include discover tasks
  ansible.builtin.include_tasks: discover.yml

- name: PROXY - create nexus auth file
  ansible.builtin.template:
    src: elysianskies_nexus.conf
    dest: /etc/apt/auth.conf.d/elysianskies_nexus.conf
    owner: root
    group: root
    mode: '0600'
  become: true
