---
- name: PROXY - discover nexus apt repository
  ansible.builtin.uri:
    url: "{{ nexus_proxy }}"
    status_code:
      - 200
      - -1
  register: discovered_nexus

- name: PROXY - create nexus auth file
  ansible.builtin.template:
    src: elysianskies_nexus.conf
    dest: /etc/apt/auth.conf.d/elysianskies_nexus.conf
    owner: root
    group: root
    mode: '0600'
  become: true
