---
output:
  elasticsearch:
    username: elastic
    password: {{ secrets.containers.elasticsearch.elastic }}
    pipeline: lab-geoip-pipeline
{% if ansible_system_vendor == "Linode" %}
    hosts:
      - https://db.proxy-int.{{ lab.domain }}:443

setup:
  dashboards:
    enabled: false
  kibana:
    host: https://data.proxy-int.{{ lab.domain }}:443
{% else %}
    hosts:
      - http://{{ elasticsearch_vlan_40_address }}:{{ ports.elasticsearch_db }}

setup:
  dashboards:
    enabled: true
  kibana:
    host: http://{{ kibana_vlan_40_address }}:{{ ports.kibana_web }}
{% endif %}

logging:
  level: info
  to_files: true
  to_syslog: false
  json: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: "3"
    permissions: "0644"

filebeat:
  config:
    modules:
      path: ${path.config}/modules.d/*.yml
  modules:
    - module: system
      syslog:
        enabled: true
        var:
          paths:
            - /var/log/syslog*
      auth:
        enabled: true
        var:
          paths:
            - /var/log/auth.log*
  inputs:
    - type: filestream
      id: container-fs
      paths:
        - /var/lib/docker/containers/*/*.log
      processors:
        - add_docker_metadata: ~
