---
output:
  elasticsearch:
    username: {{ secrets.elastic.james_austin.username }}
    password: {{ secrets.elastic.james_austin.password }}
    pipeline: elysianskies-geoip-pipeline
{% if ansible_system_vendor == "Linode" %}
    hosts:
      - https://elasticsearch.{{ assignments.nginx.networking.teine.fqdn }}:443

setup:
  dashboards:
    enabled: false
  kibana:
    host: https://kibana.{{ assignments.nginx.networking.teine.fqdn }}:443
{% else %}
    hosts:
      - http://{{ assignments.elasticsearch.networking.teine.ipv4 }}:{{ external_ports.elasticsearch_db }}

setup:
  dashboards:
    enabled: true
  kibana:
    host: http://{{ assignments.kibana.networking.teine.ipv4 }}:{{ external_ports.kibana_web }}
{% endif %}

logging:
  level: info
  to_files: true
  to_syslog: false
  json: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: "3"
    permissions: "0644"

filebeat:
  config:
    modules:
      path: ${path.config}/modules.d/*.yml
  modules:
    - module: system
      syslog:
        enabled: true
        var:
          paths:
            - /var/log/syslog*
      auth:
        enabled: true
        var:
          paths:
            - /var/log/auth.log*
  inputs:
    - type: container
      paths:
        - /var/lib/docker/containers/*/*.log
      processors:
        - add_docker_metadata: ~
