---
cycles:
  up:
    name: up
    state:
      glusterfs: started
      containers: started
      tunnels: started
      portal:
        nginx: started
        linode: started
      beats: started
    pull_local_images: true
    volumes:
      app_data: mounted
      dfs_lvm: mounted
      raid_vol: mounted

  down:
    name: down
    state:
      glusterfs: stopped
      containers: stopped
      tunnels: stopped
      portal:
        nginx: stopped
        linode: stopped
      beats: stopped
    pull_local_images: false
    volumes:
      app_data: unmounted
      dfs_lvm: unmounted
      raid_vol: unmounted
