---
cycles:
  up:
    name: up
    state:
      glusterfs: started
      containers: started
      tunnels:
        nginx: started
        openvpnas: started
      portal:
        nginx: started
        linode: started
      beats: started
    volumes:
      app_data: mounted
      dfs_lvm: mounted
      raid: mounted

  down:
    name: down
    state:
      glusterfs: stopped
      containers: stopped
      tunnels:
        nginx: stopped
        openvpnas: stopped
      portal:
        nginx: stopped
        linode: stopped
      beats: stopped
    volumes:
      app_data: unmounted
      dfs_lvm: unmounted
      raid: unmounted
