---
cycles:
  full:
    name: full
    state:
      glusterfs: started
      containers: started
      tunnels:
        nginx: started
        openvpnas: started
        gitlab: started
      portal:
        nginx: started
      beats: started
    volumes:
      app_data: mounted
      dfs_lvm: mounted
      raid: mounted

  up:
    name: up
    state:
      glusterfs: started
      containers: started
      tunnels:
        nginx: started
        openvpnas: started
        gitlab: started
      portal:
        nginx: started
      beats: started
    volumes:
      app_data: mounted
      dfs_lvm: mounted
      raid: mounted

  down:
    name: down
    state:
      glusterfs: stopped
      containers: stopped
      tunnels:
        nginx: stopped
        openvpnas: stopped
        gitlab: stopped
      portal:
        nginx: stopped
      beats: stopped
    volumes:
      app_data: unmounted
      dfs_lvm: unmounted
      raid: unmounted
