---
names:

  admin_email: j.austin.ford@gmail.com
  local_timezone: America/Denver

  ############################################################
  #     Theme : Ancient England and Arthurian Legend         #
  ############################################################

  #        ⠀⠀⠀⠀⠀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠙⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠹⣧⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⢀⣴⣿⣿⡿⠿⠛⠓⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⣤⡾⠟⠋⣁⣤⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⣷⡀⠀⠀⣀⣀⣠⣤⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣿⡇⢀⣴⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⠋⣠⣾⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣾⣿⣿⣿⣿⠟⠻⢿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⣄⣉⠁⠀⠀⠀⠀⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣤⡄⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀
  #        ⠀⠀⠀⠀⠀⠀⠀⠘⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠃⠀⠀

  ############################################################
  #                                                          #
  #   Whoso pulleth out this sword of this stone and anvil,  #
  #       is rightwise king born of all England.             #
  #                                                          #
  ############################################################

  raid: xcalibr # The Sword in the Stone, 24TB RAIDZ1.

  groups:
    raid:
      name: roundtable # Noble Knights who protect the Sword.
      id: 32600

    devops:
      name: angles # The Tribes of the Eastern Kingdoms.
      id: 32610

  users:
    host:
      super: root       # The Lord, our God Allmighty.
      admin: king       # His Majesty, Ælfræd the Great.
      iac: queen        # Powerful matriach and executor.
      engineer: knight  # Defender of the Realm, ample privileges.
      associate: squire # Meager candidate, no privileges.

    raid:
      red_ro: gawain      # Loyal knight, good friend of Arthur.
      green_rw: bedivere  # The knight who returned the Sword.
      blue_ro: tristan    # Skilled knight, warrior musician.
      black_rw: lancelot  # Most famous knight, betrayer of Arthur.

  hosts:
    docker00: eastanglia  # Kingdom of the East-Angles.
    docker01: mercia      # Kingdom of the Midlands.
    docker02: northumbria # Kingdom of the North.
    nas: wessex           # Mightiest of Saxon kingdoms.
    portal: portal        # Gateway to the World Wide Web.

  networks:
    vlan_20: rth # Earth, SMB and DFS Storage.
    vlan_30: wtr # Water, Gateway Routing.
    vlan_40: fre # Fire, Container and Host Services.
    vlan_50: air # Air, Managed Switch Configuration.
