---
ports:
  nexus_web: "32500"
  nexus_docker_hosted: "32501"
  nexus_docker_proxy: "32502"
  vault_web: "32503"
  pihole_web: "32504"
  nginx_web: "32505"
  plex_web: "32506"
  tautulli_web: "32507"
  filebrowser_web: "32508"
  elasticsearch_db: "32509"
  kibana_web: "32510"
  zoneminder_web: "32511"
  expressvpn_squid: "32512"
  expressvpn_deluge: "32513"
  gitlab_web: "32514"
  gitlab_ssh: "32515"
  openvpnas_web: "32516"
  openvpnas_vpn: "32517"
  docs_web: "32518"
  resume_web: "32519"
  fourohfour_web: "32520"
  fiveohx_web: "32521"
  fourohthree_web: "32522"
  keycloak_web: "32523"
  redis_db: "32524"
  oauth_web: "32525"
