---
profiles:
  super:
    colors:
      primary: lightyellow
      secondary: white
      tertiary: lightgrey
      vim: elflord

  admin:
    colors:
      primary: red
      secondary: white
      tertiary: lightgrey
      vim: elflord

  iac:
    colors:
      primary: purple
      secondary: white
      tertiary: lightgrey
      vim: elflord

  engineer:
    colors:
      primary: lightblue
      secondary: white
      tertiary: lightgrey
      vim: elflord

  associate:
    colors:
      primary: lightgreen
      secondary: white
      tertiary: lightgrey
      vim: elflord
