---
profiles:
  super:
    state: present
    greeting: My Lord
    colors:
      primary: lightyellow
      secondary: white
      tertiary: lightgrey
      vim: elflord

  admin:
    state: present
    greeting: Your Majesty
    colors:
      primary: red
      secondary: white
      tertiary: lightgrey
      vim: elflord

  iac:
    state: present
    greeting: Your Royal Highness
    colors:
      primary: purple
      secondary: white
      tertiary: lightgrey
      vim: elflord

  engineer:
    state: present
    greeting: Good Sir
    colors:
      primary: lightblue
      secondary: white
      tertiary: lightgrey
      vim: elflord

  associate:
    state: present
    greeting: Welcome Candidate
    colors:
      primary: lightgreen
      secondary: white
      tertiary: lightgrey
      vim: elflord
