---
- name: MAIN - include wake tasks
  ansible.builtin.include_tasks: wake.yml
  when: execute_mode.name == "up"

- name: MAIN - include poweroff tasks
  ansible.builtin.include_tasks: poweroff.yml
  when: execute_mode.name == "down"
