---
- name: POWEROFF - shutdown host
  community.general.shutdown:
  become: true

- name: POWEROFF - waiting on host port
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ wol.wait_port }}"
    state: stopped
  delegate_to: localhost
