---
- name: POWEROFF - shutdown host
  community.general.shutdown:
  become: true
  when: poweroff.enabled

- name: "POWEROFF - waiting on host port {{ wol.wait_port }}"
  delegate_to: localhost
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ wol.wait_port }}"
    state: stopped
    delay: 10
    sleep: 5
  when: poweroff.enabled
