---
- name: WAKE - send wol magic packet
  delegate_to: localhost
  community.general.wakeonlan:
    mac: "{{ wol.mac }}"
    broadcast: "{{ wol.broadcast }}"
    port: "{{ wol.port }}"
  changed_when: false

- name: WAKE - waiting on host
  ansible.builtin.wait_for_connection:
