---
services:

  ###########################################################
  # builder
  ###########################################################

  builder:
    build:
      context: .
      tags:
        - nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    profiles:
      - builder

  ###########################################################
  # ansible_playbook_site
  ###########################################################

  ansible_playbook_site:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible-playbook \
            /etc/ansible/site.yml \
            -vv
    profiles:
      - site

    environment:
      - TZ=America/Denver
      - ELISE_PROJECT_EXPRESSVPN_CONTINENT=north_america
      - ELISE_PROJECT_EXPRESSVPN_REGION=main
      - ELISE_PROJECT_EXPRESSVPN_COUNTRY=united_states
      - ELISE_PROJECT_EXPRESSVPN_SERVER=usa-denver
      - ELISE_PROJECT_MAXMIND_DOWNLOAD=no

    volumes:
      - type: bind
        source: /c/Users/austin/.docker
        target: /root/.docker
        read_only: true

      - type: volume
        source: tvault
        target: /tfstate
        read_only: false
        volume: 
          subpath: elysianskies/tfstate

    networks:
      - iac_configure

  ###########################################################
  # ansible_vault_secrets_decrypt
  ###########################################################

  ansible_vault_secrets_decrypt:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible-vault decrypt \
            /etc/ansible/group_vars/secrets.yml \
            -vv
    profiles:
      - secrets-decrypt

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    volumes:
      - type: bind
        source: /c/Users/austin/workspace/git/gitlab.home.elysianskies.com/elise/infrastructure/iac-configure/ansible/group_vars
        target: /etc/ansible/group_vars
        read_only: false

    networks:
      - iac_configure

  ###########################################################
  # ansible_vault_secrets_encrypt
  ###########################################################

  ansible_vault_secrets_encrypt:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible-vault encrypt \
            /etc/ansible/group_vars/secrets.yml \
            -vv
    profiles:
      - secrets-encrypt

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    volumes:
      - type: bind
        source: /c/Users/austin/workspace/git/gitlab.home.elysianskies.com/elise/infrastructure/iac-configure/ansible/group_vars
        target: /etc/ansible/group_vars
        read_only: false

    networks:
      - iac_configure

  ###########################################################
  # ansible_ping
  ###########################################################

  ansible_ping:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible all \
          --module-name ansible.builtin.ping \
          -vv
    profiles:
      - ping

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    networks:
      - iac_configure

  ###########################################################
  # ansible_tunnels_off
  ###########################################################

  ansible_tunnels_off:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible docker02-teine.home.elysianskies.com --become --module-name systemd --args 'state=stopped name=tunnel-nginx' ;
        ansible docker02-teine.home.elysianskies.com --become --module-name systemd --args 'state=stopped name=tunnel-openvpnas' ;
        ansible docker02-teine.home.elysianskies.com --become --module-name systemd --args 'state=stopped name=tunnel-elasticsearch' ;
        ansible docker01-teine.home.elysianskies.com --become --module-name systemd --args 'state=stopped name=tunnel-kibana'
    profiles:
      - tunnels-off

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    networks:
      - iac_configure

  ###########################################################
  # ansible_tunnels_on
  ###########################################################

  ansible_tunnels_on:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible docker02-teine.home.elysianskies.com --become --module-name systemd --args 'state=started name=tunnel-nginx' ;
        ansible docker02-teine.home.elysianskies.com --become --module-name systemd --args 'state=started name=tunnel-openvpnas' ;
        ansible docker02-teine.home.elysianskies.com --become --module-name systemd --args 'state=started name=tunnel-elasticsearch' ;
        ansible docker01-teine.home.elysianskies.com --become --module-name systemd --args 'state=started name=tunnel-kibana'
    profiles:
      - tunnels-on

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    networks:
      - iac_configure

  ###########################################################
  # ansible_reboot_elysianskies_onprem_docker
  ###########################################################

  ansible_reboot_elysianskies_onprem_docker:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible elysianskies_onprem_docker \
            --module-name ansible.builtin.reboot \
            --become
    profiles:
      - reboot-elysianskies-onprem-docker

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    networks:
      - iac_configure

  ###########################################################
  # ansible_shutdown_elysianskies_onprem_docker
  ###########################################################

  ansible_shutdown_elysianskies_onprem_docker:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible elysianskies_onprem_docker \
            --module-name community.general.shutdown \
            --become
    profiles:
      - shutdown-elysianskies-onprem-docker

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    networks:
      - iac_configure

  ###########################################################
  # ansible_wake_elysianskies_onprem_docker
  ###########################################################

  ansible_wake_elysianskies_onprem_docker:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible localhost \
            --module-name community.general.wakeonlan \
            --args \"mac='68:05:ca:30:e7:44' port=9\" \
            -vvv ;
        ansible localhost \
            --module-name community.general.wakeonlan \
            --args \"mac='68:05:ca:30:ec:86' port=9\" \
            -vvv          
    profiles:
      - wake-elysianskies-onprem-docker

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    network_mode: host

  ###########################################################
  # ansible_reboot_elysianskies_onprem_nas
  ###########################################################

  ansible_reboot_elysianskies_onprem_nas:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible elysianskies_onprem_nas \
            --module-name ansible.builtin.reboot \
            --become
    profiles:
      - reboot-elysianskies-onprem-nas

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    networks:
      - iac_configure

  ###########################################################
  # ansible_shutdown_elysianskies_onprem_nas
  ###########################################################

  ansible_shutdown_elysianskies_onprem_nas:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible elysianskies_onprem_nas \
            --module-name community.general.shutdown \
            --become
    profiles:
      - shutdown-elysianskies-onprem-nas

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    networks:
      - iac_configure

  ###########################################################
  # ansible_wake_elysianskies_onprem_nas
  ###########################################################

  ansible_wake_elysianskies_onprem_nas:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible localhost \
            --module-name community.general.wakeonlan \
            --args \"mac='10:ff:e0:00:8d:6c' port=9\" \
            -vvv
    profiles:
      - wake-elysianskies-onprem-nas

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    network_mode: host

  ###########################################################
  # ansible_reboot_elysianskies_linode
  ###########################################################

  ansible_reboot_elysianskies_linode:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible elysianskies_linode \
            --module-name ansible.builtin.reboot \
            --become
    profiles:
      - reboot-elysianskies-linode

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    networks:
      - iac_configure

  ###########################################################
  # ansible_shutdown_elysianskies_linode
  ###########################################################

  ansible_shutdown_elysianskies_linode:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible elysianskies_linode \
            --module-name community.general.shutdown \
            --become
    profiles:
      - shutdown-elysianskies-linode

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    networks:
      - iac_configure

###########################################################
# resources
###########################################################

volumes:
  tvault:
    driver_opts:
      type: cifs
      o: username=${TVAULT_USERNAME},password=${TVAULT_PASSWORD},uid=1000,gid=1000,iocharset=utf8
      device: //172.16.16.4/tvault

networks:
  iac_configure:
    name: iac_configure
