---
services:

  ############################################################
  # setup
  ############################################################

  setup:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible ${SETUP_TARGET} \
            --module-name ansible.builtin.setup \
            -vv

    profiles:
      - setup

    environment:
      - TZ=America/Denver

    volumes:
      - type: bind
        source: ${IAC_CONFIGURE_PROJECT_DIR}/tfstate
        target: /tfstate
        read_only: false

    network_mode: host

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ############################################################
  # site
  ############################################################

  site:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible-playbook \
            /etc/ansible/site.yml \
            -vv

    profiles:
      - site

    environment:
      - TZ=America/Denver
      - CYCLE_MODE=${CYCLE_MODE}
      - ELISE_PROJECT_CRON_TRIGGER=${ELISE_PROJECT_CRON_TRIGGER}
      - ELISE_PROJECT_EXPRESSVPN_CONTINENT=${ELISE_PROJECT_EXPRESSVPN_CONTINENT}
      - ELISE_PROJECT_EXPRESSVPN_REGION=${ELISE_PROJECT_EXPRESSVPN_REGION}
      - ELISE_PROJECT_EXPRESSVPN_COUNTRY=${ELISE_PROJECT_EXPRESSVPN_COUNTRY}
      - ELISE_PROJECT_EXPRESSVPN_SERVER=${ELISE_PROJECT_EXPRESSVPN_SERVER}

    volumes:
      - type: bind
        source: ${IAC_CONFIGURE_PROJECT_DIR}/approle
        target: /approle
        read_only: true

      - type: bind
        source: ${USER_KEYFILE}
        target: /root/ansible-ssh.key
        read_only: true

      - type: bind
        source: ${USER_MOUNTFILE}
        target: /root/ansible-vault-mount.txt
        read_only: true

      - type: bind
        source: ${USER_HOME}/.docker
        target: /root/.docker
        read_only: true

      - type: bind
        source: ${IAC_CONFIGURE_PROJECT_DIR}/ansible
        target: /etc/ansible
        read_only: false

    network_mode: host

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ############################################################
  # ping
  ############################################################

  ping:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible-playbook \
            /etc/ansible/linode.yml \
            --extra-vars '{"cycle_mode": "{{ cycles.up }}", "internet_check": {"status": 200}}' ;
        ansible all \
            --module-name ansible.builtin.ping \
            -vv

    profiles:
      - ping

    environment:
      - TZ=America/Denver

    volumes:
      - type: bind
        source: ${IAC_CONFIGURE_PROJECT_DIR}/ansible
        target: /etc/ansible
        read_only: false

      - type: bind
        source: ${USER_KEYFILE}
        target: /root/ssh.key
        read_only: false

      - type: bind
        source: ${IAC_CONFIGURE_PROJECT_DIR}/tfstate
        target: /tfstate
        read_only: false

    network_mode: host

    logging:
      options:
        max-size: 10m
        max-file: '10'
