---
services:

  ###########################################################
  # builder
  ###########################################################

  builder:
    build:
      context: .
      tags:
        - docker01-teine.home.elysianskies.com:32501/elise/iac-configure:main
    profiles:
      - builder

  ###########################################################
  # setup
  ###########################################################

  setup:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible all \
          --module-name ansible.builtin.setup \
          -vv
    profiles:
      - setup

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    network_mode: host

  ###########################################################
  # site
  ###########################################################

  site:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible-playbook \
            /etc/ansible/site.yml \
            -vv
    profiles:
      - site

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}
      - CYCLE_MODE=${CYCLE_MODE}
      - LINODE_TOKEN=${LINODE_TOKEN}
      - ELISE_PROJECT_EXPRESSVPN_CONTINENT=north_america
      - ELISE_PROJECT_EXPRESSVPN_REGION=main
      - ELISE_PROJECT_EXPRESSVPN_COUNTRY=united_states
      - ELISE_PROJECT_EXPRESSVPN_SERVER=usa-dallas
      - ELISE_PROJECT_MAXMIND_DOWNLOAD=no

    volumes:
      - type: bind
        source: ${USER_HOME}/.docker
        target: /root/.docker
        read_only: true

    network_mode: host

  ###########################################################
  # vault_secrets
  ###########################################################

  vault_secrets:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible-vault ${VAULT_SECRETS_MODE} \
            /etc/ansible/group_vars/secrets.yml \
            -vv
    profiles:
      - vault-secrets

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    volumes:
      - type: bind
        source: /c/Users/austin/workspace/git/gitlab.home.elysianskies.com/elise/infrastructure/iac-configure/ansible/group_vars
        target: /etc/ansible/group_vars
        read_only: false

    network_mode: host

  ###########################################################
  # ping
  ###########################################################

  ping:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/iac-configure:main
    entrypoint:
      - /bin/bash
      - -c
      - |
        /bin/container-init.sh ;
        ansible all \
          --module-name ansible.builtin.ping \
          -vv
    profiles:
      - ping

    environment:
      - TZ=America/Denver
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - B64_SSH_KEY=${B64_SSH_KEY}

    network_mode: host
