---
# Used for local deployment and development.
# Create an '.env' file within this directory
# and populate the missing key values there.

services:
  iac_configure:
    container_name: iac-configure
    build:
      context: .
    entrypoint: |
      /bin/bash -c "
        echo '${VAULT_PASSWORD}' > /root/.vault.password ;
        echo '${B64_SSH_KEY}' | base64 -d > /root/ssh.key ;
        chmod 600 /root/ssh.key ;
        ansible-playbook /etc/ansible/site.yml -vv
      "

    environment:
      - TZ=America/Denver
      - ELISE_PROJECT_EXPRESSVPN_SERVER=usa-denver
      - ELISE_PROJECT_MAXMIND_DOWNLOAD=no

    volumes:
      - type: bind
        source: /c/Users/austin/.docker
        target: /root/.docker
        read_only: true

      - type: volume
        source: tvault
        target: /tfstate
        read_only: false
        volume: 
          subpath: elysianskies/tfstate

    networks:
      - iac_configure

volumes:
  tvault:
    driver_opts:
      type: cifs
      o: username=${TVAULT_USERNAME},password=${TVAULT_PASSWORD},uid=1000,gid=1000,iocharset=utf8
      device: //172.16.16.4/tvault

networks:
  iac_configure:
    name: iac_configure
