---
- name: "CONTAINER - include container vars for {{ item.path }}"
  ansible.builtin.include_vars: "{{ item.src }}"
  no_log: true

- name: "CONTAINER - docker container {{ container.name }}"
  community.docker.docker_container:
    name: "{{ container.name }}"
    image: "{{ container.image }}"
    user: "{{ container.user }}"
    command: "{{ container.command }}"
    docker_host: "tcp://{{ container.docker_host }}:2375"
    state: "{{ container.state }}"
    restart_policy: "{{ container.restart_policy }}"
    privileged: "{{ container.privileged }}"
    detach: "{{ container.detach }}"
    interactive: "{{ container.interactive }}"
    labels:
      lab_container: "true"
      com.centurylinklabs.watchtower.enable:
        "{{ 'true' if ':' + ports.nexus_docker_hosted in container.image else 'false' }}"
    shm_size: "{{ container.shm_size }}"
    devices: "{{ container.devices }}"
    capabilities: "{{ container.capabilities }}"
    network_mode: "{{ container.network_mode }}"
    dns_servers: "{{ container.dns_servers }}"
    dns_search_domains: "{{ container.dns_search_domains }}"
    env: "{{ container.env }}"
    ports: "{{ container.ports }}"
    volumes: "{{ container.volumes }}"
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  no_log: true

- name: CONTAINER - include wait tasks
  ansible.builtin.include_tasks: wait.yml
  when: container.wait_port != "0"

- name: CONTAINER - include elastic tasks
  ansible.builtin.include_tasks: elastic.yml
  when: container.name == "elasticsearch" and ( cycle_mode.name == "full" or cycle_mode.name == "up" )

- name: CONTAINER - include vault tasks
  ansible.builtin.include_tasks: vault.yml
  when: container.name == "vault" and ( cycle_mode.name == "full" or cycle_mode.name == "up" )
