---
- name: "CONTAINER - deploy container {{ item.name }}"
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    pull: "{{ item.pull }}"
    command: "{{ item.command }}"
    docker_host: "tcp://{{ item.docker_host }}:2375"
    restart_policy: "{{ item.restart_policy }}"
    detach: "{{ item.detach }}"
    labels: "{{ item.labels }}"
    state: "{{ item.state }}"
    shm_size: "{{ item.shm_size }}"
    devices: "{{ item.devices }}"
    capabilities: "{{ item.capabilities }}"
    network_mode: "{{ item.network_mode }}"
    dns_servers: "{{ item.dns_servers }}"
    dns_search_domains: "{{ item.dns_search_domains }}"
    env: "{{ item.env }}"
    ports: "{{ item.ports }}"
    volumes: "{{ item.volumes }}"
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  no_log: true

- name: CONTAINER - include wait tasks
  ansible.builtin.include_tasks: wait.yml
  when: execute_mode.name == "deploy" and item.wait_for_port != "0"

- name: CONTAINER - docker prune
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true
  when: execute_mode.prune
