---
- name: ELASTIC - deploy ingest pipelines
  community.elastic.elastic_pipeline:
    name: "{{ pipeline.name }}"
    state: "{{ pipeline.state }}"
    description: "{{ pipeline.description }}"
    processors: "{{ pipeline.processors }}"
    auth_scheme: http
    auth_method: http_auth
    login_hosts: ["{{ elasticsearch_vlan_40_address }}"]
    login_port: "{{ ports.elasticsearch_db }}"
    login_user: elastic
    login_password: "{{ secrets.containers.elasticsearch.elastic }}"
  async: 60
  poll: 5
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  loop_control:
    loop_var: pipeline
  with_items:
    - "{{ elastic.ingest_pipelines }}"
