---
- name: MAIN - create local .docker directory
  ansible.builtin.file:
    path: /root/.docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: MAIN - manage local docker configuration
  ansible.builtin.template:
    src: config.json
    dest: /root/.docker/config.json
    owner: root
    group: root
    mode: '0644'

- name: MAIN - include container tasks
  ansible.builtin.include_tasks: container.yml
  no_log: true
  with_items:
    - "{{ containers }}"
