---
- name: MAIN - include container tasks in deploy mode
  ansible.builtin.include_tasks: container.yml
  no_log: true
  when: execute_mode.name == "deploy"
  with_items:
    - "{{ containers }}"

- name: MAIN - include container tasks in shutdown mode
  ansible.builtin.include_tasks: container.yml
  no_log: true
  when: execute_mode.name == "shutdown"
  with_items:
    - "{{ containers | reverse }}"

- name: MAIN - include container tasks in destroy mode
  ansible.builtin.include_tasks: container.yml
  no_log: true
  when: execute_mode.name == "destroy"
  with_items:
    - "{{ containers | reverse }}"

- name: MAIN - docker prune
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true
  when: execute_mode.prune
