---
- name: "WAIT - waiting on host port {{ container.wait_port }}"
  ansible.builtin.wait_for:
    host: "{{ container.docker_host }}"
    port: "{{ container.wait_port }}"
    state: "{{ cycle_mode.state.containers }}"
