---
- name: "WAIT - waiting on host port {{ item.wait_port }}"
  ansible.builtin.wait_for:
    host: "{{ item.docker_host }}"
    port: "{{ item.wait_port }}"
    state: "{{ cycle_mode.state.containers }}"
    sleep: 5
