---
europe:
  - west:
      - france:
          - france-paris-1
          - france-paris-2
          - france-strasbourg
          - france-alsace
          - france-marseille
          - jersey
      - spain:
          - spain
          - spain-barcelona
          - spain-barcelona2
      - netherlands:
          - netherlands-amsterdam
          - netherlands-rotterdam
          - netherlands-thehague
      - germany:
          - germany-frankfurt-1
          - germany-darmstadt
          - germany-nuremberg
      - switzerland:
          - switzerland
          - switzerland-2
      - luxembourg:
          - luxembourg
      - portugal:
          - portugal
      - belgium:
          - belgium
      - liechtenstein:
          - liechtenstein
      - moldova:
          - moldova
      - andorra:
          - andorra

  - north:
      - united_kingdom:
          - uk-london
          - uk-east-london
          - uk-1-docklands
          - uk-wembley
          - uk-midlands
          - isleofman
      - ireland:
          - ireland
      - sweden:
          - sweden
          - sweden2
      - finland:
          - finland
      - denmark:
          - denmark
      - norway:
          - norway
      - iceland:
          - iceland

  - south:
      - italy:
          - italy-naples
          - italy-cosenza
          - italy-milan
      - austria:
          - austria
      - greece:
          - greece
      - cyprus:
          - cyprus
      - malta:
          - malta
      - monaco:
          - monaco

  - east:
      - poland:
          - poland
      - lithuania:
          - lithuania
      - czech_republic:
          - czechrepublic
      - romania:
          - romania
      - ukraine:
          - ukraine
      - hungary:
          - hungary
      - bulgaria:
          - bulgaria
      - croatia:
          - croatia
      - slovenia:
          - slovenia
      - latvia:
          - latvia
      - albania:
          - albania
      - slovakia:
          - slovakia
      - estonia:
          - estonia
      - serbia:
          - serbia
      - macedonia:
          - macedonia
      - bosnia_and_herzegovina:
          - bosniaandherzegovina
      - belarus:
          - belarus
      - montenegro:
          - montenegro
