---
north_america:
  - main:
      - united_states:
          - usa-albuquerque
          - usa-atlanta
          - usa-chicago
          - usa-dallas
          - usa-dallas-2
          - usa-denver
          - usa-houston
          - usa-lincolnpark
          - usa-losangeles
          - usa-losangeles-2
          - usa-losangeles-3
          - usa-losangeles5
          - usa-miami
          - usa-miami-2
          - usa-newyork
          - usa-newjersey-1
          - usa-newjersey2
          - usa-newjersey-3
          - usa-phoenix
          - usa-saltlakecity
          - usa-sanfrancisco
          - usa-santa-monica
          - usa-seattle
          - usa-tampa-1
          - usa-washingtondc
      - canada:
          - canada-montreal
          - canada-toronto
          - canada-toronto-2

  - central:
      - mexico:
          - mexico
      - panama:
          - panama
      - costa_rica:
          - costarica
      - guatemala:
          - guatemala
      - honduras:
          - honduras

  - caribbean:
      - bahamas:
          - bahamas
      - dominican_republic:
          - dominicanrepublic
      - jamaica:
          - jamaica
      - puerto_rico:
          - puertorico
      - bermuda:
          - bermuda
      - trinidad_and_tobago:
          - trinidadandtobago
      - cayman_islands:
          - caymanislands
      - cuba:
          - cuba
