---
south_america:
  - east:
      - brazil:
          - brazil
          - brazil-2

  - south:
      - argentina:
          - argentina
      - uruguay:
          - uruguay

  - west:
      - chile:
          - chile
      - peru:
          - peru
      - bolivia:
          - bolivia

  - north:
      - colombia:
          - colombia
      - venezuela:
          - venezuela
      - ecuador:
          - ecuador
