---
ansible_user: "{{ secrets.docker01.privileged_user.username }}"
ansible_password: "{{ secrets.docker01.privileged_user.password }}"
ansible_become_password: "{{ secrets.docker01.privileged_user.password }}"

lan_interface:
  teine: eno1
  talamh: enp1s0f1
  uisge: bond0

poweroff:
  enabled: true

wol:
  mac: "04:42:1A:03:A4:BD"
  broadcast: "192.168.40.7"
  port: 9
  wait_port: 22
