---
ansible_python_interpreter: /usr/bin/python3

# ansible_user: "{{ names.users.host.super }}"
# ansible_password: "{{ secrets.users.host.super.docker00 }}"
# ansible_become_password: "{{ secrets.users.host.super.docker00 }}"

ansible_user: "{{ names.users.host.iac }}"
ansible_password: "{{ secrets.users.host.iac.docker00 }}"
ansible_become_password: "{{ secrets.users.host.iac.docker00 }}"

ansible_ssh_private_key_file: /automation/iac-configure.key

poweroff:
  enabled: false

lan_ints:
  vlan_30: enx9c69d3004ff3
  vlan_40: eth0

lazarus_node: true
