---
ansible_user: "{{ secrets.docker00.privileged_user.username }}"
ansible_password: "{{ secrets.docker00.privileged_user.password }}"
ansible_become_password: "{{ secrets.docker00.privileged_user.password }}"

lan_interface:
  teine: eth0

poweroff:
  enabled: false

lazarus_node: true
