---
ansible_python_interpreter: /usr/bin/python3

# ansible_user: "{{ names.users.host.super }}"
# ansible_password: "{{ secrets.users.host.super.docker01 }}"
# ansible_become_password: "{{ secrets.users.host.super.docker01 }}"

ansible_user: "{{ names.users.host.iac }}"
ansible_password: "{{ secrets.users.host.iac.docker01 }}"
ansible_become_password: "{{ secrets.users.host.iac.docker01 }}"

ansible_ssh_private_key_file: /automation/iac-configure.key

poweroff:
  enabled: true

lan_ints:
  vlan_20: bond0
  vlan_30: enp1s0f1
  vlan_40: eno1
  vlan_50: enp2s0f1

wol:
  mac: "04:42:1A:03:A4:BD"
  broadcast: "192.168.40.7"
  port: 9
  wait_port: 22
