---
############################################################

ansible_python_interpreter: /usr/bin/python3

ansible_user: "{{ names.users.privileged }}"
ansible_password: "{{ secrets.users.docker02.privileged }}"
ansible_become_password: "{{ secrets.users.docker02.privileged }}"

ansible_ssh_private_key_file: /root/ansible-ssh.key

############################################################

host_users:
  superuser:
    uid: "0"
    home_dir: /root
    group: root

  privileged:
    uid: "32612"
    home_dir: "/home/{{ names.users.privileged }}"
    group: "{{ names.users.privileged }}"

  non_privileged:
    uid: "32613"
    home_dir: "/home/{{ names.users.non_privileged }}"
    group: "{{ names.users.non_privileged }}"

poweroff:
  enabled: true

lan_ints:
  vlan_20: bond0
  vlan_30: enp1s0f1
  vlan_40: eno1
  vlan_50: enp2s0f1

wol:
  mac: "04:42:1A:06:BB:AF"
  broadcast: "192.168.40.7"
  port: 9
  wait_port: 22
