---
ansible_user: "{{ secrets.hosts.docker02.user.username }}"
ansible_password: "{{ secrets.hosts.docker02.user.password }}"
ansible_become_password: "{{ secrets.hosts.docker02.user.password }}"

lan_interface:
  teine: eno1
  talamh: enp1s0f1
  uisge: enp1s0f0

poweroff:
  enabled: true

wol:
  mac: "04:42:1A:06:BB:AF"
  broadcast: "172.16.17.7"
  port: 9
  wait_port: 22
