---
ansible_user: "{{ secrets.nas.privileged_user.username }}"
ansible_password: "{{ secrets.nas.privileged_user.password }}"
ansible_become_password: "{{ secrets.nas.privileged_user.password }}"

lan_interface:
  teine: re0

poweroff:
  enabled: true

wol:
  mac: "10:FF:E0:00:8D:6C"
  broadcast: "192.168.40.7"
  port: 9
  wait_port: 445
