---
############################################################

ansible_python_interpreter: /usr/local/bin/python3

ansible_user: "{{ names.users.non_privileged }}"

ansible_ssh_private_key_file: /root/ansible-ssh.key

############################################################

host_users:
  superuser:
    home_dir: /root
    group: wheel

  privileged:
    home_dir: "/mnt/{{ names.raid_vol.name }}/{{ names.users.privileged }}"
    group: wheel

  non_privileged:
    home_dir: "/mnt/{{ names.raid_vol.name }}/{{ names.users.non_privileged }}"
    group: builtin_guests

poweroff:
  enabled: true

lan_ints:
  vlan_20: lagg0
  vlan_30: em1
  vlan_40: re0

wol:
  mac: "10:FF:E0:00:8D:6C"
  broadcast: "192.168.40.7"
  port: 9
  wait_port: 22
