---
ansible_python_interpreter: /usr/local/bin/python3

# ansible_user: "{{ names.users.host.super }}"
# ansible_password: "{{ secrets.users.host.iac.super }}"
# ansible_become_password: "{{ secrets.users.host.iac.super }}"

ansible_user: "{{ names.users.host.iac }}"
ansible_password: "{{ secrets.users.host.iac.nas }}"
ansible_become_password: "{{ secrets.users.host.iac.nas }}"

ansible_ssh_private_key_file: /root/iac-configure.key

poweroff:
  enabled: true

lan_ints:
  vlan_20: lagg0
  vlan_30: em1
  vlan_40: re0

wol:
  mac: "10:FF:E0:00:8D:6C"
  broadcast: "192.168.40.7"
  port: 9
  wait_port: 22
