---
############################################################

ansible_python_interpreter: /usr/local/bin/python3

# ansible_user: root
# ansible_password: "{{ secrets.lab_users.nas.superuser }}"
# ansible_become_password: "{{ secrets.lab_users.nas.superuser }}"

ansible_user: "{{ names.lab_users.privileged }}"
ansible_password: "{{ secrets.lab_users.nas.privileged }}"
ansible_become_password: "{{ secrets.lab_users.nas.privileged }}"

############################################################

host_users:
  superuser:
    group: wheel

  privileged:
    uid: "32616"
    home_dir: "/mnt/{{ names.raid_vol.name }}/{{ names.lab_users.privileged }}"
    group: wheel

  nonprivileged:
    uid: "32617"
    home_dir: "/mnt/{{ names.raid_vol.name }}/{{ names.lab_users.nonprivileged }}"
    group: builtin_guests

poweroff:
  enabled: true

lan_ints:
  vlan_20: lagg0
  vlan_30: em1
  vlan_40: re0

wol:
  mac: "10:FF:E0:00:8D:6C"
  broadcast: "192.168.40.7"
  port: 9
  wait_port: 22
