---
############################################################

ansible_python_interpreter: /usr/bin/python3

# ansible_user: root
# ansible_password: "{{ secrets.lab_users.portal.superuser }}"
# ansible_become_password: "{{ secrets.lab_users.portal.superuser }}"

ansible_user: "{{ names.lab_users.privileged }}"
ansible_password: "{{ secrets.lab_users.portal.privileged }}"
ansible_become_password: "{{ secrets.lab_users.portal.privileged }}"

ansible_ssh_private_key_file: /root/ssh.key

############################################################

host_users:
  superuser:
    group: root

  privileged:
    uid: "32618"
    home_dir: "/home/{{ names.lab_users.privileged }}"
    group: "{{ names.lab_users.privileged }}"

  nonprivileged:
    uid: "32619"
    home_dir: "/home/{{ names.lab_users.nonprivileged }}"
    group: "{{ names.lab_users.nonprivileged }}"
