---
- name: main - copy authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: "{{ item.state }}"
    key: "{{ item.key }}"
  with_items:
    - "{{ ssh.authorized_keys }}"

- name: main - upload templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  become: true
  notify: main - systemctl restart ssh
  when: ansible_system_vendor != "Linode"
  with_items:
    - src: sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0644'
