server {
    server_name data.{{ lab.domain }} data.proxy-ext.{{ lab.domain }};
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass   http://{{ kibana_vlan_40_address }}:{{ ports.kibana_web }};
        auth_request /oauth2/auth;
    }

    location /oauth2/ {
        proxy_pass http://{{ oauth_vlan_40_address }}:{{ ports.oauth_web }}/oauth2/;
    }

    location /oauth2/auth {
        proxy_pass http://{{ oauth_vlan_40_address }}:{{ ports.oauth_web }}/oauth2/auth?allowed_groups=partners,operators;
        error_page 403 = $scheme://fourohthree.{{ lab.domain }};
    }
}

server {
    server_name data.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    set $external_client "N";

    if ($http_x_portal) {
        set $external_client "Y";
    }

    if ($http_x_real_ip != {{ query('community.dns.lookup', 'portal.' + lab.domain )[0] }}) {
        set $external_client "${external_client}Y";
    }

    if ($external_client = YY) {
        return 404;
    }

    location / {
        proxy_pass http://{{ kibana_vlan_40_address }}:{{ ports.kibana_web }};
    }
}
