server {
    server_name data.proxy-ext.{{ lab.domain }} data.{{ lab.domain }};
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass   http://{{ kibana_vlan_40_address }}:{{ ports.kibana_web }};
        auth_request /oauth2/auth;
    }

    location /oauth2/ {
        proxy_pass http://{{ oauth_vlan_40_address }}:{{ ports.oauth_web }}/oauth2/;
    }
}

server {
    server_name data.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    set $external_client "N";

    if ($http_x_portal) {
        set $external_client "Y";
    }

    if ($http_x_real_ip != {{ ( lookup('ansible.builtin.file', '/tmp/portal.json') | from_json )['ip_address'] }}) {
        set $external_client "${external_client}Y";
    }

    if ($external_client = YY) {
        return 404;
    }

    location / {
        proxy_pass http://{{ kibana_vlan_40_address }}:{{ ports.kibana_web }};
    }
}
