server {
    server_name dl.{{ lab.domain }};
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass      http://{{ deluge_vlan_40_address }}:{{ ports.expressvpn_deluge }};
        auth_request    /oauth2/auth;
        sub_filter
        '</head>'
        '<link rel="stylesheet" type="text/css" href="https://halianelf.github.io/Deluge-Dark/deluge.css">
        </head>';
        sub_filter_once on;
    }

    location /oauth2/ {
        proxy_pass http://{{ oauth_vlan_40_address }}:{{ ports.oauth_web }}/oauth2/;
    }
}

server {
    server_name dl.{{ nginx_vlan_40_fqdn }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass      http://{{ deluge_vlan_40_address }}:{{ ports.expressvpn_deluge }};
        sub_filter
        '</head>'
        '<link rel="stylesheet" type="text/css" href="https://halianelf.github.io/Deluge-Dark/deluge.css">
        </head>';
        sub_filter_once on;
    }
}
