server {
    server_name docker-proxy.{{ lab.domain }};
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass http://{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_hosted }};
    }
}

server {
    server_name docker-proxy.{{ nginx_vlan_40_fqdn }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_hosted }};
    }
}
