server {
    server_name docker-hosted.{{ lab.domain }} docker-hosted.proxy-ext.{{ lab.domain }};
    listen      443 ssl;

    if ($general_allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass http://{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_hosted }};
    }
}

server {
    server_name docker-hosted.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_hosted }};
    }
}
