server {
    server_name eyes.proxy-ext.{{ lab.domain }} eyes.{{ lab.domain }};
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    if ($allowed_city = no) {
        return 403;
    }

    location / {
        proxy_pass http://{{ zoneminder_vlan_40_address }}:{{ ports.zoneminder_web }};
        return     301 $scheme://$host/zm/;
    }

    location /zm/ {
        proxy_pass   http://{{ zoneminder_vlan_40_address }}:{{ ports.zoneminder_web }}/zm/;
        auth_request /oauth2/auth;
    }

    location /oauth2/ {
        proxy_pass http://{{ oauth_vlan_40_address }}:{{ ports.oauth_web }}/oauth2/;
    }
}

server {
    server_name eyes.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ zoneminder_vlan_40_address }}:{{ ports.zoneminder_web }};
        return     301 $scheme://$host/zm/;
    }

    location /zm/ {
        proxy_pass http://{{ zoneminder_vlan_40_address }}:{{ ports.zoneminder_web }}/zm/;
    }
}
