server {
    server_name fiveohx.{{ lab.domain }};
    listen      443 ssl;

    location / {
        proxy_pass http://{{ fiveohx_vlan_40_address }}:{{ ports.fiveohx_web }};
    }
}

server {
    server_name fiveohx.{{ nginx_vlan_40_fqdn }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ fiveohx_vlan_40_address }}:{{ ports.fiveohx_web }};
    }
}
