server {
    server_name fourohfour.proxy-ext.{{ lab.domain }} fourohfour.{{ lab.domain }};
    listen      443 ssl;

    location / {
        proxy_pass http://{{ fourohfour_vlan_40_address }}:{{ ports.fourohfour_web }};
    }
}

server {
    server_name fourohfour.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ fourohfour_vlan_40_address }}:{{ ports.fourohfour_web }};
    }
}
