server {
    server_name fourohthree.{{ lab.domain }};
    listen      443 ssl;

    location / {
        proxy_pass http://{{ fourohthree_vlan_40_address }}:{{ ports.fourohthree_web }};
    }
}

server {
    server_name fourohthree.{{ nginx_vlan_40_fqdn }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ fourohthree_vlan_40_address }}:{{ ports.fourohthree_web }};
    }
}
