server {
    server_name kv.proxy-ext.{{ lab.domain }} kv.{{ lab.domain }};
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass http://{{ vault_vlan_40_address }}:{{ ports.vault_web }};
    }
}

server {
    server_name kv.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ vault_vlan_40_address }}:{{ ports.vault_web }};
    }
}
