server {
    server_name media.proxy-ext.{{ lab.domain }} media.{{ lab.domain }};
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass http://{{ plex_vlan_40_address }}:{{ ports.plex_web }};
    }
}

server {
    server_name media.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ plex_vlan_40_address }}:{{ ports.plex_web }};
    }
}
