server {
    server_name nas.home.elysianskies.com;
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    if ($allowed_city = no) {
        return 403;
    }

    location / {
        proxy_pass   https://192.168.40.5:443;
        auth_request /oauth2/auth;
    }

    location /oauth2/ {
        proxy_pass http://{{ assignments.oauth.networking.teine.ipv4 }}:{{ external_ports.oauth_web }}/oauth2/;
    }
}

server {
    server_name nas.{{ assignments.nginx.networking.teine.fqdn }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass https://192.168.40.5:443;
    }
}
