server {
    server_name nexus-proxy.home.elysianskies.com;
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass http://{{ assignments.nexus.networking.teine.ipv4 }}:{{ external_ports.nexus_docker_proxy }};
    }
}

server {
    server_name nexus-proxy.{{ assignments.nginx.networking.teine.fqdn }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ assignments.nexus.networking.teine.ipv4 }}:{{ external_ports.nexus_docker_proxy }};
    }
}
