server {
    server_name nginx.{{ assignments.nginx.networking.teine.fqdn }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        stub_status;
    }
}
