server {
    server_name oauth.home.elysianskies.com;
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass http://{{ assignments.oauth.networking.teine.ipv4 }}:{{ external_ports.oauth_web }};
    }
}
