server {
    server_name pihole.home.elysianskies.com;
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass   http://{{ assignments.pihole.networking.teine.ipv4 }}:{{ external_ports.pihole_web }};
        rewrite      ^/$ /admin redirect;
        auth_request /oauth2/auth;
    }

    location /oauth2/ {
        proxy_pass http://{{ assignments.oauth.networking.teine.ipv4 }}:{{ external_ports.oauth_web }}/oauth2/;
    }
}

server {
    server_name pihole.{{ assignments.nginx.networking.teine.fqdn }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ assignments.pihole.networking.teine.ipv4 }}:{{ external_ports.pihole_web }};
        rewrite    ^/$ /admin redirect;
    }
}
