server {
    server_name ping.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        return 200 '{"proxy": "internal", "response": "pong"}\n';

        add_header Content-Type application/json;
    }
}
