server {
    server_name resume.{{ lab.domain }} resume.proxy-ext.{{ lab.domain }};
    listen      443 ssl;

    location / {
        proxy_pass http://{{ resume_vlan_40_address }}:{{ ports.resume_web }};
    }

    location /api/public/dl {
        proxy_pass http://{{ filebrowser_vlan_40_address }}:{{ ports.filebrowser_web }}/api/public/dl;
    }
}

server {
    server_name resume.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ resume_vlan_40_address }}:{{ ports.resume_web }};
    }

    location /api/public/dl {
        proxy_pass http://{{ filebrowser_vlan_40_address }}:{{ ports.filebrowser_web }}/api/public/dl;
    }
}
