server {
    server_name *.proxy-ext.{{ lab.domain }} *.{{ lab.domain }};
    listen      443 ssl;
}

server {
    server_name proxy-ext.{{ lab.domain }};
    listen      443 ssl;

    location / {
        return 301 https://docs.proxy-ext.{{ lab.domain }};
    }
}

server {
    server_name {{ lab.domain }};
    listen      443 ssl;

    location / {
        return 301 https://docs.{{ lab.domain }};
    }
}
