server {
    server_name *.proxy-ext.{{ lab.domain }} *.{{ lab.domain }};
    listen      443 ssl;
}

server {
    server_name {{ lab.domain }} proxy-ext.{{ lab.domain }};
    listen      443 ssl;

    location / {
        return 301 $scheme://docs.proxy-ext.$host;
    }
}
