server {
    server_name *.{{ lab.domain }} *.{{ nginx_vlan_40_fqdn }};
    listen      443 ssl;
}

server {
    server_name {{ lab.domain }} {{ nginx_vlan_40_fqdn }};
    listen      443 ssl;

    location / {
        return 301 $scheme://docs.$host;
    }
}
