server {
    server_name storage.{{ lab.domain }} storage.proxy-ext.{{ lab.domain }};
    listen      443 ssl;

    if ($general_allowed_country = no) {
        return 403;
    }

    if ($general_allowed_city = no) {
        return 403;
    }

    location / {
        proxy_pass   https://{{ nas_vlan_40_address }}:443;
        auth_request /oauth2/auth;

        proxy_http_version 1.1;

        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $http_connection;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP         $http_x_real_ip;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host  $http_x_forwarded_host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Forwarded-Ssl   $http_x_forwarded_ssl;
    }

    location /oauth2/ {
        proxy_pass http://{{ oauth_vlan_40_address }}:{{ ports.oauth_web }}/oauth2/;
    }

    location /oauth2/auth {
        proxy_pass http://{{ oauth_vlan_40_address }}:{{ ports.oauth_web }}/oauth2/auth?allowed_groups=partners;
        error_page 403 = $scheme://fourohthree.{{ lab.domain }};
    }
}

server {
    server_name storage.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass https://{{ nas_vlan_40_address }}:443;

        proxy_http_version 1.1;

        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $http_connection;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP         $http_x_real_ip;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host  $http_x_forwarded_host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Forwarded-Ssl   $http_x_forwarded_ssl;
    }
}
