server {
    server_name track-captions.{{ lab.domain }} track-captions.proxy-ext.{{ lab.domain }};
    listen      443 ssl;

    if ($general_allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass   http://{{ bazarr_vlan_40_address }}:{{ ports.gluetun_bazarr }};
        auth_request /oauth2/auth;
    }

    location /oauth2/ {
        proxy_pass http://{{ oauth_vlan_40_address }}:{{ ports.oauth_web }}/oauth2/;
    }

    location /oauth2/auth {
        proxy_pass http://{{ oauth_vlan_40_address }}:{{ ports.oauth_web }}/oauth2/auth?allowed_groups=partners;
        error_page 403 = $scheme://fourohthree.{{ lab.domain }};
    }
}

server {
    server_name track-captions.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ bazarr_vlan_40_address }}:{{ ports.gluetun_bazarr }};
    }
}
