server {
    server_name track-requests.{{ lab.domain }} track-requests.proxy-ext.{{ lab.domain }};
    listen      443 ssl;

    if ($allowed_country = no) {
        return 403;
    }

    location / {
        proxy_pass http://{{ seerr_vlan_40_address }}:{{ ports.gluetun_seerr }};
    }
}

server {
    server_name track-requests.proxy-int.{{ lab.domain }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 404;
    }

    location / {
        proxy_pass http://{{ seerr_vlan_40_address }}:{{ ports.gluetun_seerr }};
    }
}
