---
glusterfs:
  peers:
    - "{{ docker01_vlan_20_address }}"
    - "{{ docker02_vlan_20_address }}"

  dfs:
    name: lab_dfs
    state: started
    bricks: /mnt/dfs_lvm/lab_dfs
    replicas: 2
    transport: tcp

  service:
    state: "{{ cycle_mode.state.glusterfs }}"

  mount:
    state: "{{ cycle_mode.volumes.app_data }}"
