---
- name: "DIRECTORIES - copy container directory {{ item.path }}"
  ansible.builtin.file:
    path: "{{ lab.dirs.config }}/{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ lab.dirs.owner }}"
    group: "{{ lab.dirs.group }}"
    mode: "{{ lab.dirs.mode }}"
  become: true
