---
- name: "DIRECTORIES - copy container directory {{ item.path }}"
  ansible.builtin.file:
    path: "/elysianskies/configurations/{{ item.path }}"
    state: "{{ item.state }}"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true
