---
- name: GEOIP - download database
  ansible.builtin.get_url:
    url: "https://download.maxmind.com/app/geoip_download?edition_id={{ item }}&license_key={{ secrets.external.maxmind.license_key }}&suffix=tar.gz"
    dest: /root/geoip
    owner: root
    group: root
    mode: '0640'
  when: internet_found == 'yes'
  become: true

- name: GEOIP - discover directory
  ansible.builtin.command: |
    /bin/bash -c '
      find /root/geoip -type f -name '*.tar.gz' \
        | grep '{{ item }}' \
        | sort \
        | tail -1 \
        | cut -d '/' -f4 \
        | cut -d '.' -f1
    '
  register: db_directory
  become: true
  changed_when: false

- name: GEOIP - unarchive database
  ansible.builtin.unarchive:
    src: "/root/geoip/{{ db_directory.stdout }}.tar.gz"
    dest: /root/geoip
    owner: "{{ assignments.nginx.uid }}"
    group: "{{ assignments.nginx.uid }}"
    mode: '0640'
    remote_src: true
  become: true

- name: GEOIP - move database
  ansible.builtin.copy:
    src: "/root/geoip/{{ db_directory.stdout }}/{{ item }}.mmdb"
    dest: "{{ lab.dirs.app_data }}/nginx/geoip/{{ item }}.mmdb"
    owner: "{{ assignments.nginx.uid }}"
    group: "{{ assignments.nginx.uid }}"
    mode: '0640'
    remote_src: true
  become: true
