---
- name: MAXMIND - ensure geoip download directory
  ansible.builtin.file:
    path: "{{ folder_container_app }}/nginx/geoip"
    state: directory
    mode: '0750'
    owner: "{{ assignments.nginx.uid }}"
    group: "{{ assignments.nginx.uid }}"
  become: true

- name: MAXMIND - find old geoip databases
  ansible.builtin.find:
    paths: "{{ folder_container_app }}/nginx/geoip"
    recurse: true
    file_type: any
    age: "{{ maxmind.rotate_after_days }}d"
  become: true
  register: old_geoip_files

- name: MAXMIND - remove old geoip databases
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  become: true
  with_items:
    - "{{ old_geoip_files.files }}"

- name: MAXMIND - include geoip tasks
  ansible.builtin.include_tasks: geoip.yml
  with_items:
    - GeoLite2-ASN
    - GeoLite2-City
    - GeoLite2-Country
