---
- name: MAXMIND - ensure geoip download directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/geoip"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: MAXMIND - rotate old geoip databases
  ansible.builtin.command: |
    find /home/{{ ansible_user }}/geoip -mindepth 1 -ctime +{{ maxmind.rotate_after_days }} -exec rm -rf {} \;
  changed_when: false
  become: true

- name: MAXMIND - include geoip tasks
  ansible.builtin.include_tasks: geoip.yml
  with_items:
    - GeoLite2-ASN
    - GeoLite2-City
    - GeoLite2-Country
