---
- name: SSL_DEPLOY - copy ssl certificate
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ assignments.nginx.uid }}"
    group: "{{ assignments.nginx.uid }}"
    mode: "{{ item.mode }}"
  become: true
  no_log: true
  notify: MAIN - docker restart nginx
  with_items:
    - src: nginx.crt
      dest: "{{ folder_container_config }}/nginx/nginx.crt"
      mode: '0644'

    - src: nginx.crt.key
      dest: "{{ folder_container_config }}/nginx/nginx.crt.key"
      mode: '0600'
