---
- name: SSL_DISCOVER - discover deployed nginx certificate
  ansible.builtin.uri:
    url: "http://{{ assignments.gitlab.networking.teine.fqdn }}:{{ external_ports.gitlab_web }}/api/v4/projects/2/terraform/state/certificates_portal_nginx"
    headers:
      PRIVATE-TOKEN: "{{ secrets.gitlab.pat_api }}"
    method: GET
    return_content: true
    status_code:
      - 404
      - 200
      - -1
  no_log: true
  register: discovered_tls

- name: SSL_DISCOVER - include ssl_deploy tasks
  ansible.builtin.include_tasks: ssl_deploy.yml
  when: discovered_tls.status == 200
