---
- name: SSL_DEPLOY - copy ssl certificates
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  become: true
  no_log: true
  notify: MAIN - docker restart nginx
  with_items:
    - content: |
        {{ discovered_tls.content | from_json | json_query('outputs.certificate_certificate_pem.value') }}
        {{ discovered_tls.content | from_json | json_query('outputs.certificate_issuer_pem.value') }}
      dest: /elysianskies/configurations/nginx/nginx.crt
      mode: '0644'

    - content: |
        {{ discovered_tls.content | from_json | json_query('outputs.certificate_private_key_pem.value') }}
      dest: /elysianskies/configurations/nginx/nginx.crt.key
      mode: '0600'
