---
- name: SSL_DEPLOY - copy ssl certificates
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  become: true
  no_log: true
  notify: MAIN - systemctl restart nginx
  with_items:
    - content: |
        {{ lookup('ansible.builtin.file', '/tfstate/portal_nginx.json')["outputs"]["certificate_certificate_pem"]["value"] }}
        {{ lookup('ansible.builtin.file', '/tfstate/portal_nginx.json')["outputs"]["certificate_issuer_pem"]["value"] }}
      dest: /etc/nginx/nginx.crt
      mode: '0644'

    - content: |
        {{ lookup('ansible.builtin.file', '/tfstate/portal_nginx.json')["outputs"]["certificate_private_key_pem"]["value"] }}
      dest: /etc/nginx/nginx.crt.key
      mode: '0600'
