---
- name: "TEMPLATES - resolve expressvpn server"
  expressvpn_selector:
    continent: north_america
    region: main
    country: united_states
    server: random
  register: expressvpn_selected_server

- name: "TEMPLATES - copy container template {{ item.path }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/elysianskies/configurations/{{ item.path }}"
    mode: '0755'
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  become: true
  notify: "MAIN - docker restart {{ item.path.split('/')[0] }}"
