---
- name: "TEMPLATES - copy container template {{ item.path }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ folder_container_config }}/{{ item.path }}"
    mode: "0750"
  become: true
  notify: "MAIN - docker restart {{ item.path.split('/')[0] }}"
