---
secrets:
  users:
    host:
      super:
        docker00: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/super/docker/00')
          | first ).data['PASSWORD']
          }}
        docker01: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/super/docker/01')
          | first ).data['PASSWORD']
          }}
        docker02: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/super/docker/02')
          | first ).data['PASSWORD']
          }}
        portal: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/super/portal')
          | first ).data['PASSWORD']
          }}

      admin:
        docker00: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/admin/docker/00')
          | first ).data['PASSWORD']
          }}
        docker01: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/admin/docker/01')
          | first ).data['PASSWORD']
          }}
        docker02: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/admin/docker/02')
          | first ).data['PASSWORD']
          }}
        portal: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/admin/portal')
          | first ).data['PASSWORD']
          }}

      iac:
        docker00: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/iac/docker/00')
          | first ).data['PASSWORD']
          }}
        docker01: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/iac/docker/01')
          | first ).data['PASSWORD']
          }}
        docker02: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/iac/docker/02')
          | first ).data['PASSWORD']
          }}
        nas: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/iac/nas')
          | first ).data['PASSWORD']
          }}
        portal: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/iac/portal')
          | first ).data['PASSWORD']
          }}

      engineer:
        docker00: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/engineer/docker/00')
          | first ).data['PASSWORD']
          }}
        docker01: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/engineer/docker/01')
          | first ).data['PASSWORD']
          }}
        docker02: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/engineer/docker/02')
          | first ).data['PASSWORD']
          }}
        portal: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/engineer/portal')
          | first ).data['PASSWORD']
          }}

      associate:
        docker00: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/associate/docker/00')
          | first ).data['PASSWORD']
          }}
        docker01: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/associate/docker/01')
          | first ).data['PASSWORD']
          }}
        docker02: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/associate/docker/02')
          | first ).data['PASSWORD']
          }}
        portal: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/host/associate/portal')
          | first ).data['PASSWORD']
          }}

    raid:
      red_rw: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/raid/red_rw')
        | first ).data['PASSWORD']
        }}
      red_ro: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/raid/red_ro')
        | first ).data['PASSWORD']
        }}
      blue_ro: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/raid/blue_ro')
        | first ).data['PASSWORD']
        }}
      green_rw: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/raid/green_rw')
        | first ).data['PASSWORD']
        }}
      black_rw: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/raid/black_rw')
        | first ).data['PASSWORD']
        }}

  containers:
    nexus:
      username: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/nexus/users/admin')
        | first ).data['USERNAME']
        }}
      password: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/nexus/users/admin')
        | first ).data['PASSWORD']
        }}

    plex:
      plex_claim: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/plex')
        | first ).data['CLAIM_TOKEN']
        }}

    elasticsearch:
      kibana_system: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/elasticsearch/users/kibana_system')
        | first ).data['PASSWORD']
        }}
      elastic: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/elasticsearch/users/elastic')
        | first ).data['PASSWORD']
        }}

    kibana:
      encryption_keys:
        encrypted_saved_objects: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'containers/kibana/encryption_keys')
          | first ).data['ENCRYPTED_SAVED_OBJECTS']
          }}
        reporting: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'containers/kibana/encryption_keys')
          | first ).data['REPORTING']
          }}
        security: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'containers/kibana/encryption_keys')
          | first ).data['SECURITY']
          }}

    zoneminder:
      gmail_app_password: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/zoneminder/smtp')
        | first ).data['GMAIL_APP_PASSWORD']
        }}

    gluetun:
      username: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/gluetun/users/expressvpn')
        | first ).data['USERNAME']
        }}
      password: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/gluetun/users/expressvpn')
        | first ).data['PASSWORD']
        }}

    gitlab:
      gmail_app_password: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/gitlab/smtp')
        | first ).data['GMAIL_APP_PASSWORD']
        }}
      runner_authentication_token:
        runner_admin: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'containers/gitlab/runner_authentication_tokens/runner_admin')
          | first ).data['TOKEN']
          }}
        runner_user: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'containers/gitlab/runner_authentication_tokens/runner_user')
          | first ).data['TOKEN']
          }}
      superuser: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/gitlab/users/admin')
        | first ).data['PASSWORD']
        }}

    redis:
      password: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/redis')
        | first ).data['PASSWORD']
        }}

    oauth:
      cookie_secret: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/oauth')
        | first ).data['COOKIE_SECRET']
        }}
      client_secret: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/oauth')
        | first ).data['CLIENT_SECRET']
        }}

    vault:
      unseal_keys: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/vault')
        | first ).data['UNSEAL_KEYS']
        }}

  external:
    linode:
      token: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'external/linode')
        | first ).data['API_TOKEN']
        }}

    maxmind:
      license_key: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'external/maxmind')
        | first ).data['LICENSE_KEY']
        }}
