---
secrets:
  users:
    docker00:
      superuser: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/superuser/onprem_docker')
        | first ).data['DOCKER00']
        }}
      privileged: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/privileged/onprem_docker')
        | first ).data['DOCKER00']
        }}
      non_privileged: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/non_privileged/onprem_docker')
        | first ).data['DOCKER00']
        }}

    docker01:
      superuser: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/superuser/onprem_docker')
        | first ).data['DOCKER01']
        }}
      privileged: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/privileged/onprem_docker')
        | first ).data['DOCKER01']
        }}
      non_privileged: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/non_privileged/onprem_docker')
        | first ).data['DOCKER01']
        }}

    docker02:
      superuser: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/superuser/onprem_docker')
        | first ).data['DOCKER02']
        }}
      privileged: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/privileged/onprem_docker')
        | first ).data['DOCKER02']
        }}
      non_privileged: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/non_privileged/onprem_docker')
        | first ).data['DOCKER02']
        }}

    nas:
      privileged: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/privileged/onprem_nas')
        | first ).data['NAS']
        }}

      raid_vol:
        red_ro: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/raid_vol/red_ro')
          | first ).data['PASSWORD']
          }}
        green_rw: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/raid_vol/green_rw')
          | first ).data['PASSWORD']
          }}
        blue_ro: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/raid_vol/blue_ro')
          | first ).data['PASSWORD']
          }}
        black_rw: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'users/raid_vol/black_rw')
          | first ).data['PASSWORD']
          }}

    portal:
      superuser: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/superuser/linode')
        | first ).data['PORTAL']
        }}
      privileged: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/privileged/linode')
        | first ).data['PORTAL']
        }}
      non_privileged: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'users/non_privileged/linode')
        | first ).data['PORTAL']
        }}

  containers:
    nexus:
      username: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/nexus/users/admin')
        | first ).data['USERNAME']
        }}
      password: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/nexus/users/admin')
        | first ).data['PASSWORD']
        }}

    nginx:
      tls:
        ca: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'certificates/nginx')
          | first ).data['CA_PEM_B64']
          }}
        cert: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'certificates/nginx')
          | first ).data['CERT_PEM_B64']
          }}
        key: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'certificates/nginx')
          | first ).data['KEY_PEM_B64']
          }}

    plex:
      plex_claim: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/plex')
        | first ).data['CLAIM_TOKEN']
        }}

    elasticsearch:
      kibana_system: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/elasticsearch/users/kibana_system')
        | first ).data['PASSWORD']
        }}
      elastic: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/elasticsearch/users/elastic')
        | first ).data['PASSWORD']
        }}

    kibana:
      encryption_keys:
        encrypted_saved_objects: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'containers/kibana/encryption_keys')
          | first ).data['ENCRYPTED_SAVED_OBJECTS']
          }}
        reporting: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'containers/kibana/encryption_keys')
          | first ).data['REPORTING']
          }}
        security: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'containers/kibana/encryption_keys')
          | first ).data['SECURITY']
          }}

    zoneminder:
      gmail_app_password: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/zoneminder/smtp')
        | first ).data['GMAIL_APP_PASSWORD']
        }}

    expressvpn:
      username: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/expressvpn/users/admin')
        | first ).data['USERNAME']
        }}
      password: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/expressvpn/users/admin')
        | first ).data['PASSWORD']
        }}

      tls:
        ca: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'certificates/expressvpn')
          | first ).data['CA_PEM_B64']
          }}
        cert: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'certificates/expressvpn')
          | first ).data['CERT_PEM_B64']
          }}
        key: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'certificates/expressvpn')
          | first ).data['KEY_PEM_B64']
          }}
        auth: {{
          ( secrets_data
          | selectattr('path', 'equalto', 'certificates/expressvpn')
          | first ).data['AUTH_PEM_B64']
          }}

    deluge:
      salt: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/deluge')
        | first ).data['SALT']
        }}
      hash: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/deluge')
        | first ).data['HASH']
        }}

    gitlab:
      runner_authentication_token: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/gitlab/runner')
        | first ).data['RUNNER_AUTHENTICATION_TOKEN']
        }}
      superuser: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/gitlab/users/admin')
        | first ).data['PASSWORD']
        }}

    redis:
      password: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/redis')
        | first ).data['PASSWORD']
        }}

    oauth:
      cookie_secret: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/oauth')
        | first ).data['COOKIE_SECRET']
        }}
      client_secret: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/oauth')
        | first ).data['CLIENT_SECRET']
        }}

    vault:
      unseal_keys: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'containers/vault')
        | first ).data['UNSEAL_KEYS']
        }}

  external:
    linode:
      token: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'external/linode')
        | first ).data['API_TOKEN']
        }}

    maxmind:
      license_key: {{
        ( secrets_data
        | selectattr('path', 'equalto', 'external/maxmind')
        | first ).data['LICENSE_KEY']
        }}
