dev tun
fast-io
persist-key
persist-tun
nobind
remote {{ expressvpn_selected_server.selected_server }}-ca-version-2.expressnetw.com 1195
remote-random
pull
comp-lzo no
tls-client
verify-x509-name Server name-prefix
ns-cert-type server
key-direction 1
route-method exe
route-delay 2
tun-mtu 1500
fragment 1300
mssfix 1200
verb 3
cipher AES-256-CBC
auth SHA512
sndbuf 524288
rcvbuf 524288
auth-user-pass /vpn/vpn.credentials
<cert>
{{ secrets.containers.expressvpn.tls.cert | b64decode }}
</cert>
<key>
{{ secrets.containers.expressvpn.tls.key | b64decode }}
</key>
<tls-auth>
{{ secrets.containers.expressvpn.tls.auth | b64decode }}
</tls-auth>
<ca>
{{ secrets.containers.expressvpn.tls.ca | b64decode }}
</ca>
