---
lab_dirs:
  application_directory: /elysianskies/application_data
  configuration_directory: /elysianskies/configurations

cycle_modes:
  up:
    name: up
    state:
      glusterfs: started
      containers: started
      tunnels: started
      portal:
        nginx: started
        linode: started
      beats: started
    gateway_masquerade: present
    pull_local_images: true
    volumes:
      app_data: mounted
      dfs_lvm: mounted
      tvault: mounted

  down:
    name: down
    state:
      glusterfs: stopped
      containers: stopped
      tunnels: stopped
      portal:
        nginx: stopped
        linode: stopped
      beats: stopped
    gateway_masquerade: absent
    pull_local_images: false
    volumes:
      app_data: unmounted
      dfs_lvm: unmounted
      tvault: unmounted

docker_hosts:
  host_1:
    networking:
      talamh:
        fqdn: docker01-talamh.home.elysianskies.com
        ipv4: "172.16.14.2"
      uisge:
        fqdn: docker01-uisge.home.elysianskies.com
        ipv4: "172.16.16.2"
      teine:
        fqdn: docker01-teine.home.elysianskies.com
        ipv4: "172.16.17.2"

  host_2:
    networking:
      talamh:
        fqdn: docker02-talamh.home.elysianskies.com
        ipv4: "172.16.14.3"
      uisge:
        fqdn: docker02-uisge.home.elysianskies.com
        ipv4: "172.16.16.3"
      teine:
        fqdn: docker02-teine.home.elysianskies.com
        ipv4: "172.16.17.3"

  host_3:
    networking:
      teine:
        fqdn: docker03-teine.home.elysianskies.com
        ipv4: "172.16.17.4"

assignments:
  nexus: "{{ docker_hosts.host_1 }}"
  pihole: "{{ docker_hosts.host_2 }}"
  plex: "{{ docker_hosts.host_1 }}"
  tautulli: "{{ docker_hosts.host_2 }}"
  filebrowser: "{{ docker_hosts.host_2 }}"
  elasticsearch: "{{ docker_hosts.host_1 }}"
  kibana: "{{ docker_hosts.host_1 }}"
  zoneminder: "{{ docker_hosts.host_2 }}"
  expressvpn: "{{ docker_hosts.host_1 }}"
  squid: "{{ docker_hosts.host_1 }}"
  deluge: "{{ docker_hosts.host_1 }}"
  gitlab: "{{ docker_hosts.host_2 }}"
  runner: "{{ docker_hosts.host_2 }}"
  openvpnas: "{{ docker_hosts.host_2 }}"
  docs: "{{ docker_hosts.host_1 }}"
  resume: "{{ docker_hosts.host_1 }}"
  fourohfour: "{{ docker_hosts.host_2 }}"
  fiveohx: "{{ docker_hosts.host_1 }}"
  fourohthree: "{{ docker_hosts.host_2 }}"
  barbossa: "{{ docker_hosts.host_2 }}"
  keycloak: "{{ docker_hosts.host_1 }}"
  redis: "{{ docker_hosts.host_2 }}"
  oauth: "{{ docker_hosts.host_1 }}"
  nginx: "{{ docker_hosts.host_2 }}"
  lazarus: "{{ docker_hosts.host_3 }}"

external_ports:
  nexus_web: "32500"
  nexus_docker_hosted: "32501"
  nexus_docker_proxy: "32502"
  pihole_web: "32503"
  plex_web: "32504"
  tautulli_web: "32505"
  filebrowser_web: "32506"
  elasticsearch_db: "32507"
  kibana_web: "32508"
  zoneminder_web: "32509"
  expressvpn_squid: "32510"
  expressvpn_deluge: "32511"
  gitlab_web: "32512"
  openvpnas_web: "32513"
  openvpnas_vpn: "32514"
  docs_web: "32515"
  resume_web: "32516"
  fourohfour_web: "32517"
  fiveohx_web: "32518"
  fourohthree_web: "32519"
  keycloak_web: "32520"
  redis_db: "32521"
  oauth_web: "32522"
  nginx_web: "32523"

task_globals:
  discover_uri:
    status_code: [-1, 200, 502]
