---
sudoers:
  cmd_paths:
    - /bin
    - /usr/bin

  aliases:
    users:
      lab_sudoers:
        - "{{ names.users.privileged }}"

    cmds:
      general_nopasswd:
        - netstat

      general_restricted:
        - chmod
        - chown
        - df
        - du
        - su
        - passwd

      docker_nopasswd:
        - ls
        - events
        - ps
        - logs
        - pull
        - stats
        - start
        - restart
        - top
        - system df

      docker_restricted:
        - inspect
        - export
        - exec
        - run
        - push
        - rename
        - kill
        - rm
        - rmi
        - prune

      fs_restricted:
        - ls
        - vi
        - vim
        - cat
        - nano
        - less
        - more

    dirs:
      fs_restricted:
        - lab
        - dfs_lvm
        - "{{ names.raid_vol.name }}"
        - root
        - sudoers
        - filebeat
        - metricbeat
        - docker
