---
sudoers:
  cmd_paths:
    - /bin
    - /usr/bin

  aliases:
    users:
      lab_sudoers:
        - "{{ names.lab_users.privileged }}"

    cmds:
      general_nopasswd:
        - netstat

      general_restricted:
        - chmod
        - chown
        - df
        - du
        - su
        - passwd

      docker_nopasswd:
        - ls
        - events
        - ps
        - logs
        - pull
        - stats
        - start
        - restart
        - top
        - system df

      docker_restricted:
        - inspect
        - export
        - exec
        - run
        - push
        - rename
        - kill
        - rm
        - rmi
        - prune

      fs_restricted:
        - ls
        - vi
        - vim
        - cat
        - nano
        - less
        - more

    dirs:
      fs_restricted:
        - /lab
        - /mnt/dfs_lvm
        - "/mnt/{{ names.raid_vol.name }}/root"
        - /root
        - /etc/sudoers
        - /usr/local/etc/sudoers
        - /etc/filebeat
        - /etc/metricbeat
        - /var/lib/docker
