root={{ names.svc_email }}
mailhub={{ ssmtp.email_server }}
rewriteDomain=
UseSTARTTLS=YES
AuthUser={{ names.svc_email }}
AuthPass={{ secrets.containers.zoneminder.gmail_app_password }}
FromLineOverride=YES
