---
- name: "FILES - copy user bash file - {{ item }}"
  ansible.builtin.template:
    src: "{{ file_name }}"
    dest: "{{ host_users[item].home_dir }}/{{ file_name }}"
    owner: "{{ names.users[item] }}"
    group: "{{ host_users[item].group }}"
    mode: '0750'
  loop_control:
    loop_var: file_name
  when: role_users[item].state == "present"
  become: true
  with_items:
    - .bash_profile
    - .vimrc
    - .hushlogin
