---
- name: "FILES - copy user bash file - {{ item }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ host_users[file_user].home_dir }}/{{ item }}"
    owner: "{{ names.users[file_user] }}"
    group: "{{ host_users[file_user].group }}"
    mode: '0750'
  loop_control:
    loop_var: file_user
  when: role_users[file_user].state == "present"
  become: true
  with_items:
    - superuser
    - privileged
    - non_privileged
