---
- name: MAIN - create raid_vol group
  ansible.builtin.group:
    name: "{{ names.raid_vol.group.name }}"
    gid: "{{ names.raid_vol.group.gid }}"
    state: present
  become: true
  when: inventory_hostname != "nas"

- name: MAIN - include superuser tasks
  ansible.builtin.include_tasks: superuser.yml

- name: MAIN - include nonprivileged_user tasks
  ansible.builtin.include_tasks: nonprivileged_user.yml

- name: MAIN - include nonprivileged_user tasks
  ansible.builtin.include_tasks: nonprivileged_user.yml
