---
- name: MAIN - include docker_hosts tasks
  ansible.builtin.include_tasks: docker_hosts.yml
  when: inventory_hostname != "nas"

- name: MAIN - include files tasks
  ansible.builtin.include_tasks: files.yml
  with_items:
    - superuser
    - privileged
    - non_privileged
