---
- name: NON_PRIVILEGED - manage non_privileged user
  ansible.builtin.user:
    name: "{{ names.users.non_privileged }}"
    shell: /bin/bash
    uid: "{{ host_users.non_privileged.uid }}"
    state: "{{ role_users.non_privileged.state }}"
    groups: ''
    force: true
    remove: true
  become: true

- name: NON_PRIVILEGED - manage non_privileged user password
  ansible.builtin.user:
    name: "{{ names.users.non_privileged }}"
    password: "{{ secrets.users[inventory_hostname].non_privileged | password_hash('sha512') }}"
  become: true
  changed_when: false
  when: role_users.non_privileged.state == "present"

- name: NON_PRIVILEGED - copy non_privileged user ssh key
  ansible.posix.authorized_key:
    user: "{{ names.users.non_privileged }}"
    key: "{{ role_users.non_privileged.public_key }}"
    state: present
  when: role_users.non_privileged.state == "present"
  become: true
