---
- name: PRIVILEGED_USER - manage privileged user
  ansible.builtin.user:
    name: "{{ names.lab_users.privileged }}"
    shell: /bin/bash
    uid: "{{ host_users.privileged.uid }}"
    state: "{{ lab_users.privileged.state }}"
    groups: sudo
    force: true
    remove: true
  become: true
  when: inventory_hostname != "nas"

- name: PRIVILEGED_USER - manage privileged user password
  ansible.builtin.user:
    name: "{{ names.lab_users.privileged }}"
    password: "{{ secrets.lab_users[inventory_hostname].privileged | password_hash('sha512') }}"
  become: true
  changed_when: false
  when: lab_users.privileged.state == "present" and inventory_hostname != "nas"

- name: PRIVILEGED_USER - copy privileged user ssh key
  ansible.posix.authorized_key:
    user: "{{ names.lab_users.privileged }}"
    key: "{{ lab_users.privileged.public_key }}"
    state: present
  when: lab_users.privileged.state == "present" and inventory_hostname != "nas"
  become: true

- name: PRIVILEGED_USER - copy privileged user bash files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ host_users.privileged.home_dir }}/{{ item }}"
    owner: "{{ names.lab_users.privileged }}"
    group: "{{ host_users.privileged.group }}"
    mode: '0750'
  vars:
    colorscheme: "{{ lab_users.privileged.colors.vim }}"
  when: lab_users.privileged.state == "present"
  become: true
  with_items:
    - .bash_profile
    - .vimrc
    - .hushlogin
