server {
    server_name fourohfour.home.elysianskies.com;
    listen      443 ssl;

    location / {
        proxy_pass http://{{ assignments.fourohfour.networking.teine.ipv4 }}:{{ external_ports.fourohfour_web }};
    }
}

server {
    server_name fourohfour.{{ assignments.nginx.networking.teine.fqdn }};
    listen      443 ssl;

    location / {
        proxy_pass http://{{ assignments.fourohfour.networking.teine.ipv4 }}:{{ external_ports.fourohfour_web }};
    }
}
