server {
    server_name gitlab.home.elysianskies.com;
    listen      443 ssl;

    if ($allowed_country = no) {
        return 301 $scheme://fourohthree.home.elysianskies.com;
    }

    location / {
        proxy_pass   http://{{ assignments.gitlab.networking.teine.ipv4 }}:{{ external_ports.gitlab_web }};
        auth_request /oauth2/auth;
    }

    location /oauth2/ {
        proxy_pass http://{{ assignments.oauth.networking.teine.ipv4 }}:{{ external_ports.oauth_web }}/oauth2/;
    }
}

server {
    server_name gitlab.{{ assignments.nginx.networking.teine.fqdn }};
    listen      443 ssl;

    if ($http_x_portal) {
        return 301 https://fourohfour.home.elysianskies.com;
    }

    location / {
        proxy_pass http://{{ assignments.gitlab.networking.teine.ipv4 }}:{{ external_ports.gitlab_web }};
    }
}
