---
############################################################
# nexus
############################################################

############################################################
# Software repository manager, primarily used for storing
# and managing software artifacts like JAR files, Docker
# images, NPM packages, and other build outputs. It acts as
# a central location for developers to access, distribute,
# and collaborate on software components, offering features
# like access control, versioning, and build integration.
############################################################

container:
  name: nexus
  image: sonatype/nexus3:3.68.1
  pull: "{{ containers_globals.pull_images.remote }}"
  user: "{{ assignments.nexus.uid }}:{{ assignments.nexus.uid }}"
  command:
    - /opt/sonatype/nexus/bin/nexus
    - run
  docker_host: "{{ nexus_vlan_40_address }}"
  state: "{{ cycle_mode.state.containers }}"
  restart_policy: unless-stopped
  privileged: false
  detach: true
  interactive: false
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
  ports:
    - "{{ nexus_vlan_40_address }}:{{ ports.nexus_web }}:8081/tcp"
    - "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_hosted }}:{{ ports.nexus_docker_hosted }}/tcp"
    - "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_proxy }}:{{ ports.nexus_docker_proxy }}/tcp"
  volumes:
    - "{{ lab.dirs.app_data }}/nexus/data:/nexus-data:rw"
  wait_port: "{{ ports.nexus_docker_proxy }}"
