---
############################################################
# pihole
############################################################

############################################################
# Network-wide ad blocker that acts as a DNS sinkhole. It
# blocks unwanted content such as ads and trackers, by
# filtering DNS requests, improving network performance and
# enhancing privacy.
############################################################

container:
  name: pihole
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_proxy }}/pihole/pihole:2025.08.0"
  pull: "{{ containers_globals.pull_images.remote }}"
  user: "0:0"
  command: null
  docker_host: "{{ pihole_vlan_40_address }}"
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities:
    - net_admin
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
    PIHOLE_UID: "{{ assignments.pihole.uid }}"
    PIHOLE_GID: "{{ assignments.pihole.uid }}"
  ports:
    - "{{ pihole_vlan_20_address }}:53:53/udp"
    - "{{ pihole_vlan_30_address }}:53:53/udp"
    - "{{ pihole_vlan_40_address }}:53:53/udp"
    - "{{ pihole_vlan_40_address }}:{{ ports.pihole_web }}:80/tcp"
  volumes:
    - "{{ lab.dirs.app_data }}/pihole/data:/etc/pihole:rw"
  wait_port: "{{ ports.pihole_web }}"
