---
###########################################################
# vault
###########################################################

###########################################################
# Tool for securely accessing secrets via a unified
# interface and tight access control.
###########################################################

container:
  name: vault
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_proxy }}/vault:1.13.3"
  user: "0:{{ assignments.vault.uid }}"
  command:
    - vault
    - server
    - -config=/vault/config.json
  docker_host: "{{ vault_vlan_40_address }}"
  state: "{{ cycle_mode.state.containers }}"
  restart_policy: unless-stopped
  privileged: false
  detach: true
  interactive: false
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities:
    - IPC_LOCK
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
  ports:
    - "{{ vault_vlan_40_address }}:{{ ports.vault_web }}:8200/tcp"
  volumes:
    - "{{ lab.dirs.config }}/vault/config.json:/vault/config.json:ro"
    - "{{ lab.dirs.app_data }}/vault/file:/vault/file:rw"
  wait_port: "{{ ports.vault_web }}"
