---
###########################################################
# nginx
###########################################################

###########################################################
# Powerful open-source software that functions as a web
# server, reverse proxy, load balancer, mail proxy, and
# HTTP cache. It's known for its high performance,
# stability, and low resource utilization, making it a
# popular choice for handling large amounts of traffic and
# complex web applications.
###########################################################

container:
  name: nginx
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_proxy }}/anroe/nginx-geoip2:1.22.1-geoip2-3.4"
  pull: "{{ containers_globals.pull_images.remote }}"
  user: "0:0"
  command:
    - nginx
    - -g
    - daemon off;
  docker_host: "{{ nginx_vlan_40_address }}"
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
  ports:
    - "{{ nginx_vlan_30_address }}:443:443/tcp"
    - "{{ nginx_vlan_40_address }}:443:443/tcp"
  volumes:
    - "{{ lab.dirs.app_data }}/nginx/geoip:/etc/nginx/geoip:rw"
    - "{{ lab.dirs.config }}/nginx/nginx.crt:/etc/nginx/nginx.crt:ro"
    - "{{ lab.dirs.config }}/nginx/nginx.crt.key:/etc/nginx/nginx.crt.key:ro"
    - "{{ lab.dirs.config }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "{{ lab.dirs.config }}/nginx/conf.d:/etc/nginx/conf.d:ro"
  wait_port: "443"
