---
###########################################################
# plex
###########################################################

###########################################################
# Media server software and a free streaming service that
# allows users to organize, stream, and share their
# personal media collections across various devices. It
# also offers a free, ad-supported streaming service with
# live TV and on-demand content from partners like
# Lionsgate and MGM.
###########################################################

container:
  name: plex
  image: "{{ assignments.nexus.networking.teine.ipv4 }}:{{ external_ports.nexus_docker_proxy }}/plexinc/pms-docker:1.42.1.10060-4e8b05daf"
  pull: "{{ containers_globals.pull_images.remote }}"
  command: null
  docker_host: "{{ assignments.plex.networking.teine.ipv4 }}"
  restart_policy: "{{ containers_globals.restart_policy }}"
  detach: "{{ containers_globals.detach }}"
  labels: "{{ containers_globals.labels }}"
  state: "{{ containers_globals.state }}"
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ containers_globals.env.TZ }}"
    PLEX_UID: "{{ containers_globals.env.PUID }}"
    PLEX_GID: "{{ containers_globals.env.PGID }}"
    PLEX_CLAIM: "{{ secrets.plex.plex_claim }}"
    ADVERTISE_IP: |
      http://192.168.60.6:{{ external_ports.plex_web }},
      http://{{ assignments.plex.networking.teine.ipv4 }}:{{ external_ports.plex_web }},
      https://plex.home.elysianskies.com
    ALLOWED_NETWORKS: |
      192.168.30.0/29,
      192.168.40.0/29,
      192.168.60.0/27
  ports:
    - "{{ assignments.plex.networking.talamh.ipv4 }}:{{ external_ports.plex_web }}:32400/tcp"
    - "{{ assignments.plex.networking.teine.ipv4 }}:{{ external_ports.plex_web }}:32400/tcp"
  volumes:
    - "{{ lab_dirs.application_directory }}/plex/Application Support:/config/Library/Application Support:rw"
    - /tmp/transcode:/transcode:rw
    - /mnt/xcalibr-plex_libraries:/plex_libraries:ro
  wait_port: "{{ external_ports.plex_web }}"
