---
###########################################################
# tautulli
###########################################################

###########################################################
# Free, open-source web application that acts as a
# monitoring and analytics tool for Plex Media Server. It
# provides detailed statistics and insights into your Plex
# usage, allowing you to track who is watching what, when,
# and how. Tautulli also offers customizable notifications
# and can generate reports, making it a valuable tool for
# Plex administrators.
###########################################################

container:
  name: tautulli
  image: "{{ assignments.nexus.networking.teine.ipv4 }}:{{ external_ports.nexus_docker_proxy }}/linuxserver/tautulli:amd64-v2.15.3-ls199"
  pull: "{{ containers_globals.pull_images.remote }}"
  command: null
  docker_host: "{{ assignments.tautulli.networking.teine.ipv4 }}"
  restart_policy: "{{ containers_globals.restart_policy }}"
  detach: "{{ containers_globals.detach }}"
  labels: "{{ containers_globals.labels }}"
  state: "{{ containers_globals.state }}"
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ containers_globals.env.TZ }}"
  ports:
    - "{{ assignments.tautulli.networking.teine.ipv4 }}:{{ external_ports.tautulli_web }}:8181/tcp"
  volumes:
    - "{{ lab_dirs.application_directory }}/tautulli/config:/config:rw"
  wait_port: "{{ external_ports.tautulli_web }}"
