---
###########################################################
# kibana
###########################################################

###########################################################
# Free and open-source data visualization and exploration
# tool, primarily used to work with data stored in
# Elasticsearch. It allows users to analyze, visualize, and
# interact with data through dashboards, charts, and other
# visualizations, making it a key component of the Elastic
# Stack.
###########################################################

container:
  name: kibana
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_proxy }}/elastic/kibana:{{ lab.elastic_version }}"
  pull: "{{ containers_globals.pull_images.remote }}"
  user: "1000:{{ assignments.kibana.uid }}"
  command:
    - /usr/local/bin/kibana-docker
  docker_host: "{{ kibana_vlan_40_address }}"
  state: "{{ cycle_mode.state.containers }}"
  detach: true
  interactive: false
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
  ports:
    - "{{ kibana_vlan_40_address }}:{{ ports.kibana_web }}:5601/tcp"
  volumes:
    - "{{ lab.dirs.config }}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
  wait_port: "{{ ports.kibana_web }}"
