---
###########################################################
# expressvpn
###########################################################

###########################################################
# Virtual private network (VPN) service that enhances
# online privacy and security by encrypting internet
# traffic and masking your IP address and location. It
# creates a secure, encrypted tunnel between your device
# and the internet, making it difficult for third parties
# to track your online activity or access your data.
###########################################################

container:
  name: expressvpn
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_proxy }}/dperson/openvpn-client:amd64"
  pull: "{{ containers_globals.pull_images.remote }}"
  user: "0:0"
  command:
    - -d
    - -f ""
  docker_host: "{{ expressvpn_vlan_40_address }}"
  state: "{{ containers_globals.state }}"
  shm_size: "{{ containers_globals.shm_size }}"
  devices:
    - /dev/net/tun
  capabilities:
    - net_admin
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
  ports:
    - "{{ expressvpn_vlan_40_address }}:{{ ports.expressvpn_squid }}:3128/tcp"
    - "{{ expressvpn_vlan_30_address }}:{{ ports.expressvpn_squid }}:3128/tcp"
    - "{{ expressvpn_vlan_40_address }}:{{ ports.expressvpn_deluge }}:8112/tcp"
  volumes:
    - "{{ lab.dirs.config }}/expressvpn/vpn:/vpn:ro"
  wait_port: "0"
