---
###########################################################
# squid
###########################################################

###########################################################
# Caching and forwarding web proxy server. It acts as an
# intermediary between clients and servers, offering
# features like caching frequently accessed content,
# controlling access to websites, and optimizing traffic
# flow. Squid is often used to improve network performance,
# enhance security, and manage internet access.
###########################################################

container:
  name: squid
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_proxy }}/sameersbn/squid:3.5.27-2"
  pull: "{{ containers_globals.pull_images.remote }}"
  user: "0:0"
  command: null
  docker_host: "{{ squid_vlan_40_address }}"
  state: "{{ cycle_mode.state.containers }}"
  detach: true
  interactive: false
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: container:expressvpn
  dns_servers: []
  dns_search_domains: []
  env:
    TZ: "{{ names.local_timezone }}"
  ports: []
  volumes:
    - "{{ lab.dirs.config }}/squid/squid.conf:/etc/squid/squid.conf:ro"
  wait_port: "{{ ports.expressvpn_squid }}"
