---
###########################################################
# fiveohx
###########################################################

###########################################################
# Nginx static page for handling 5xx errors.
###########################################################

container:
  name: fiveohx
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_hosted }}/elise/static-website-fiveohx:main"
  user: "{{ assignments.fiveohx.uid }}:{{ assignments.fiveohx.uid }}"
  command:
    - httpd-foreground
  docker_host: "{{ fiveohx_vlan_40_address }}"
  state: "{{ cycle_mode.state.containers }}"
  restart_policy: unless-stopped
  privileged: false
  detach: true
  interactive: false
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
  ports:
    - "{{ fiveohx_vlan_40_address }}:{{ ports.fiveohx_web }}:80/tcp"
  volumes: []
  wait_port: "{{ ports.fiveohx_web }}"
