---
###########################################################
# barbossa
###########################################################

###########################################################
# Conduit service component to the Plex Ingest Media
# Pipeline ( PIMP ).
###########################################################

container:
  name: barbossa
  image: "{{ assignments.nexus.networking.teine.ipv4 }}:{{ external_ports.nexus_docker_hosted }}/elise/barbossa:main"
  pull: "{{ containers_globals.pull_images.local }}"
  command:
    - python3
    - src
    - ingest-media
  docker_host: "{{ assignments.barbossa.networking.teine.ipv4 }}"
  restart_policy: "{{ containers_globals.restart_policy }}"
  detach: "{{ containers_globals.detach }}"
  labels: "{{ containers_globals.labels }}"
  state: "{{ containers_globals.state }}"
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ containers_globals.env.TZ }}"
    DELUGE_PASSWORD: "{{ secrets.deluge.password }}"
    PLEX_TOKEN: "{{ secrets.plex.token }}"
  ports: []
  volumes:
    - /mnt/tvault/deluge:/downloads:rw
    - /mnt/tvault/video/plex_libraries:/plex_libraries:rw
  wait_port: "0"
