---
###########################################################
# fourohthree
###########################################################

###########################################################
# Nginx static page for handling 403 errors.
###########################################################

container:
  name: fourohthree
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_hosted }}/elise/static-website-fourohthree:main"
  user: "{{ assignments.fourohthree.uid }}:{{ assignments.fourohthree.uid }}"
  command:
    - httpd-foreground
  docker_host: "{{ fourohthree_vlan_40_address }}"
  state: "{{ cycle_mode.state.containers }}"
  restart_policy: unless-stopped
  privileged: false
  detach: true
  interactive: false
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
  ports:
    - "{{ fourohthree_vlan_40_address }}:{{ ports.fourohthree_web }}:80/tcp"
  volumes: []
  wait_port: "{{ ports.fourohthree_web }}"
