---
###########################################################
# barbossa
###########################################################

###########################################################
# Conduit service component to the Plex Ingest Media
# Pipeline ( PIMP ).
###########################################################

container:
  name: barbossa
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_hosted }}/elise/barbossa:main"
  pull: "{{ containers_globals.pull_images.local }}"
  user: "{{ assignments.barbossa.uid }}:{{ names.raid_vol.group.gid }}"
  command:
    - python3
    - src
    - ingest-media
  docker_host: "{{ barbossa_vlan_40_address }}"
  state: "{{ cycle_mode.state.containers }}"
  restart_policy: unless-stopped
  detach: true
  interactive: false
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
    DELUGE_PASSWORD: "{{ secrets.containers.deluge.password }}"
    PLEX_TOKEN: "{{ secrets.containers.plex.token }}"
  ports: []
  volumes:
    - "/mnt/{{ names.raid_vol.name }}-black:/downloads:rw"
    - "/mnt/{{ names.raid_vol.name }}-red:/plex_libraries:rw"
  wait_port: "0"
