---
###########################################################
# nginx
###########################################################

###########################################################
# Powerful open-source software that functions as a web
# server, reverse proxy, load balancer, mail proxy, and
# HTTP cache. It's known for its high performance,
# stability, and low resource utilization, making it a
# popular choice for handling large amounts of traffic and
# complex web applications.
###########################################################

container:
  name: nginx
  image: "{{ assignments.nexus.networking.teine.ipv4 }}:{{ external_ports.nexus_docker_proxy }}/anroe/nginx-geoip2:1.22.1-geoip2-3.4"
  pull: "{{ containers_globals.pull_images.remote }}"
  command:
    - nginx
    - -g
    - daemon off;
  docker_host: "{{ assignments.nginx.networking.teine.ipv4 }}"
  restart_policy: "{{ containers_globals.restart_policy }}"
  detach: "{{ containers_globals.detach }}"
  labels: "{{ containers_globals.labels }}"
  state: "{{ containers_globals.state }}"
  shm_size: "{{ containers_globals.shm_size }}"
  devices: []
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ containers_globals.env.TZ }}"
  ports:
    - "{{ assignments.nginx.networking.teine.ipv4 }}:443:443/tcp"
  volumes:
    - "{{ lab_dirs.configuration_directory }}/nginx/nginx.crt:/etc/nginx/nginx.crt:ro"
    - "{{ lab_dirs.configuration_directory }}/nginx/nginx.crt.key:/etc/nginx/nginx.crt.key:ro"
    - "{{ lab_dirs.configuration_directory }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "{{ lab_dirs.configuration_directory }}/nginx/conf.d:/etc/nginx/conf.d:ro"
    - "{{ lab_dirs.application_directory }}/nginx/geoip:/etc/nginx/geoip:rw"
  wait_port: "443"
