---
###########################################################
# lazarus
###########################################################

###########################################################
# Power event management system which executes
# elise/infrastructure/iac-configure in cycle modes.
###########################################################

container:
  name: lazarus
  image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_hosted }}/elise/lazarus:main"
  user: "0:{{ assignments.lazarus.uid }}"
  command:
    - python3
    - src
  docker_host: "{{ lazarus_vlan_40_address }}"
  state: started
  restart_policy: unless-stopped
  privileged: false
  detach: true
  interactive: false
  shm_size: "{{ containers_globals.shm_size }}"
  devices:
    - /dev/usb/hiddev0
    - /dev/usb/hiddev1
  capabilities: []
  network_mode: "{{ containers_globals.network_mode }}"
  dns_servers: "{{ containers_globals.dns_servers }}"
  dns_search_domains: "{{ containers_globals.dns_search_domains }}"
  env:
    TZ: "{{ names.local_timezone }}"
    ELASTICSEARCH_ENDPOINT: "{{ elasticsearch_vlan_40_address }}:{{ ports.elasticsearch_db }}"
  ports: []
  volumes:
    - "{{ folder_secrets_approle }}/lazarus.json:/approle/lazarus.json:ro"
    - "{{ folder_container_app }}/lazarus/data:/lazarus/data:rw"
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /tmp:/tmp:rw
  wait_port: "0"
