---
cluster:
  name: lab_elastic

network:
  host: 0.0.0.0

node:
  name: localhost

xpack:
  security:
    enabled: true

discovery:
  type: single-node

ingest:
  geoip:
    downloader:
      enabled: true
