---
- name: MAIN - create docker volumes
  community.docker.docker_volume:
    name: "{{ item.name }}"
    docker_host: "tcp://{{ item.docker_host }}:2375"
    driver_options:
      type: cifs
      o:
        "username={{ item.username }},\
        password={{ item.password }},\
        uid=0,\
        gid={{ names.raid_vol.group.gid }},\
        dir_mode=0770,\
        file_mode=0770,\
        iocharset=utf8,\
        soft,\
        timeout=10"
      device: "//{{ item.host }}/{{ item.name }}"
  no_log: true
  with_items:
    - "{{ volumes.cifs_mounts }}"
