---
containers_globals:
  restart_policy: unless-stopped
  pull_images:
    local: "{{ cycle_mode.pull_local_images }}"
    remote: false
  detach: true
  labels:
    elysianskies_container: "true"
  state: "{{ cycle_mode.state.containers }}"
  shm_size: 64M
  network_mode: bridge
  dns_servers:
    - "192.168.30.6"
    - "8.8.8.8"
  dns_search_domains:
    - home.elysianskies.com
  env:
    TZ: America/Denver
    PUID: "1000"
    PGID: "1066"

elastic:
  ingest_pipelines:
    - name: elysianskies-geoip-pipeline
      state: present
      description: GeoIP Ingest Pipeline for Portal remote hosts
      processors:
        - geoip:
            database_file: GeoLite2-City.mmdb
            field: source.ip
            target_field: source.geo
            ignore_missing: true

        - geoip:
            database_file: GeoLite2-ASN.mmdb
            field: source.ip
            target_field: source.as
            ignore_missing: true

        - geoip:
            database_file: GeoLite2-City.mmdb
            field: destination.ip
            target_field: destination.geo
            ignore_missing: true

        - geoip:
            database_file: GeoLite2-ASN.mmdb
            field: destination.ip
            target_field: destination.as
            ignore_missing: true
