---
containers_globals:
  restart_policy: unless-stopped
  pull_images:
    local: "{{ cycle_mode.pull_local_images }}"
    remote: false
  detach: true
  labels:
    elysianskies_container: "true"
  state: "{{ cycle_mode.state.containers }}"
  shm_size: 64M
  network_mode: bridge
  dns_servers:
    - "172.16.14.4"
    - "8.8.8.8"
  dns_search_domains:
    - home.elysianskies.com
  env:
    TZ: America/Denver
