load_module      /usr/lib/nginx/modules/ngx_http_geoip2_module.so;
user             nginx;
worker_processes auto;
error_log        /var/log/nginx/error.log notice;
pid              /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    geoip2 /etc/nginx/geoip/GeoLite2-Country.mmdb {
        $geoip2_data_country_name source=$http_x_real_ip country names en;
    }

    map $geoip2_data_country_name $allowed_country {
        default         no;
{% for geoip_country in nginx.geoip_whitelists.country %}
        '{{ geoip_country }}' yes;
{% endfor %}
    }

    geoip2 /etc/nginx/geoip/GeoLite2-City.mmdb {
        $geoip2_data_city_name source=$http_x_real_ip city names en;
    }

    map $geoip2_data_city_name $allowed_city {
        default     no;
{% for geoip_city in nginx.geoip_whitelists.city %}
        '{{ geoip_city }}' yes;
{% endfor %}
    }

    default_type                  application/octet-stream;
    log_format                    main '$remote_addr - $remote_user [$time_local] "$request" '
                                       '$status $body_bytes_sent "$http_referer" '
                                       '"$http_user_agent" "$http_x_real_ip"';
    access_log                    /var/log/nginx/access.log main;
    sendfile                      on;
    keepalive_timeout             65;
    server_names_hash_bucket_size 128;
    client_max_body_size          {{ nginx.client_max_body_size }};
    large_client_header_buffers   8 64k;

    ssl_certificate     /etc/nginx/nginx.crt;
    ssl_certificate_key /etc/nginx/nginx.crt.key;

    proxy_http_version 1.1;

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP         $http_x_real_ip;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host  $http_x_forwarded_host;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header X-Forwarded-Ssl   $http_x_forwarded_ssl;

    error_page 401 = /oauth2/sign_in?rd=$scheme://$host$request_uri;
    error_page 403 = $scheme://fourohthree.{{ lab.domain }};
    error_page 404 = $scheme://fourohfour.{{ lab.domain }};
    error_page 500 = $scheme://fiveohx.{{ lab.domain }};

    include /etc/nginx/mime.types;
    include /etc/nginx/conf.d/*.conf;
}
