---
server:
  publicBaseUrl: https://data.{{ lab.domain }}
  host: 0.0.0.0

elasticsearch:
  username: {{ secrets.containers.elasticsearch.kibana_system.username }}
  password: {{ secrets.containers.elasticsearch.kibana_system.password }}
  hosts:
    - http://{{ elasticsearch_vlan_40_address }}:{{ ports.elasticsearch_db }}

xpack:
  encryptedSavedObjects:
    encryptionKey: {{ secrets.containers.kibana.encryption_keys.encrypted_saved_objects }}
  reporting:
    encryptionKey: {{ secrets.containers.kibana.encryption_keys.reporting }}
  security:
    encryptionKey: {{ secrets.containers.kibana.encryption_keys.security }}
