---
- name: MAIN - set hostname
  ansible.builtin.hostname:
    name: "{{ names.hosts[inventory_hostname] }}.{{ lab.domain }}"
  become: true
  notify: MAIN - reboot

- name: MAIN - flush handlers
  ansible.builtin.meta: flush_handlers

- name: MAIN - install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  become: true

- name: MAIN - include ssl_deploy tasks
  ansible.builtin.include_tasks: ssl_deploy.yml

- name: MAIN - configure nginx
  ansible.builtin.template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0755'
  become: true
  notify: MAIN - systemctl restart nginx

- name: MAIN - ensure nginx daemon
  ansible.builtin.systemd:
    name: nginx
    state: "{{ nginx.service_state }}"
    enabled: false
  become: true

- name: MAIN - ensure ssh gateway ports
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ # GatewayPorts'
    line: GatewayPorts yes
  become: true
  notify: MAIN - systemctl restart ssh

- name: MAIN - include fail2ban tasks
  ansible.builtin.include_tasks: fail2ban.yml
