---
- name: MAIN - set hostname
  ansible.builtin.hostname:
    name: portal
  become: true
  notify: MAIN - reboot

- name: MAIN - flush handlers
  ansible.builtin.meta: flush_handlers

- name: MAIN - install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  become: true

- name: MAIN - include ssl_deploy tasks
  ansible.builtin.include_tasks: ssl_deploy.yml

- name: MAIN - configure nginx
  ansible.builtin.copy:
    content: |
      server {
          server_name                home.elysianskies.com *.home.elysianskies.com;
          listen                     443 ssl;
          ssl_certificate            /etc/nginx/nginx.crt;
          ssl_certificate_key        /etc/nginx/nginx.crt.key;
          proxy_http_version         1.1;
          proxy_set_header           Upgrade    $http_upgrade;
          proxy_set_header           Connection $http_connection;
          proxy_set_header Host      $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Portal  true;

          location / {
              proxy_pass https://127.0.0.1:{{ external_ports.nginx_web }};
          }
      }
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0755'
  notify: MAIN - systemctl restart nginx
  become: true

- name: MAIN - ensure nginx daemon
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  become: true

- name: MAIN - ensure ssh gateway ports
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ # GatewayPorts'
    line: GatewayPorts yes
  become: true
  notify: MAIN - systemctl restart ssh
