---
- name: SSL_DEPLOY - fetch elysianskies tfstate
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.file', '/tfstate/elysianskies.json') }}"
  no_log: true
  register: elysianskies_tfstate

- name: SSL_DEPLOY - copy ssl certificate
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  become: true
  no_log: true
  notify: MAIN - systemctl restart nginx
  with_items:
    - src: nginx.crt
      dest: /etc/nginx/nginx.crt
      mode: '0644'

    - src: nginx.crt.key
      dest: /etc/nginx/nginx.crt.key
      mode: '0600'
