---
- name: SSL_DEPLOY - fetch ssl certificate
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.file', '/tfstate/elysianskies.json') }}"
  no_log: true
  register: ssl_certificate

- name: SSL_DEPLOY - copy ssl certificate
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  become: true
  no_log: true
  notify: MAIN - systemctl restart nginx
  with_items:
    - content: |
        {{ ssl_certificate.msg.outputs.tls_nginx_certificate_certificate_pem.value }}
        {{ ssl_certificate.msg.outputs.tls_nginx_certificate_issuer_pem.value }}
      dest: /etc/nginx/nginx.crt
      mode: '0644'

    - content: |
        {{ ssl_certificate.msg.outputs.tls_nginx_certificate_private_key_pem.value }}
      dest: /etc/nginx/nginx.crt.key
      mode: '0600'
