---
expressvpn_servers:

###############################################
# north america
###############################################

  north_america:
    main:
      united_states:
        - usa-albuquerque
        - usa-atlanta
        - usa-chicago
        - usa-dallas
        - usa-dallas-2
        - usa-denver
        - usa-houston
        - usa-lincolnpark
        - usa-losangeles
        - usa-losangeles-2
        - usa-losangeles-3
        - usa-losangeles5
        - usa-miami
        - usa-miami-2
        - usa-newyork
        - usa-newjersey-1
        - usa-newjersey2
        - usa-newjersey-3
        - usa-phoenix
        - usa-saltlakecity
        - usa-sanfrancisco
        - usa-santa-monica
        - usa-seattle
        - usa-tampa-1
        - usa-washingtondc
      canada:
        - canada-montreal
        - canada-toronto
        - canada-toronto-2

    central:
      mexico:
        - mexico
      panama:
        - panama
      costa_rica:
        - costarica
      guatemala:
        - guatemala
      honduras:
        - honduras

    caribbean:
      bahamas:
        - bahamas
      dominican_republic:
        - dominicanrepublic
      jamaica:
        - jamaica
      puerto_rico:
        - puertorico
      bermuda:
        - bermuda
      trinidad_and_tobago:
        -trinidadandtobago
      cayman_islands:
        - caymanislands
      cuba:
        - cuba

###############################################
# europe
###############################################

  europe:
    west:
      france:
        - france-paris-1
        - france-paris-2
        - france-strasbourg
        - france-alsace
        - france-marseille
        - jersey
      spain:
        - spain
        - spain-barcelona
        - spain-barcelona2
      netherlands:
        - netherlands-amsterdam
        - netherlands-rotterdam
        - netherlands-thehague
      germany:
        - germany-frankfurt-1
        - germany-darmstadt
        - germany-nuremberg
      switzerland:
        - switzerland
        - switzerland-2
      luxembourg:
        - luxembourg
      portugal:
        - portugal
      belgium:
        - belgium
      liechtenstein:
        - liechtenstein
      moldova:
        - moldova
      andorra:
        - andorra

    north:
      united_kingdom:
        - uk-london
        - uk-east-london
        - uk-1-docklands
        - uk-wembley
        - uk-midlands
        - isleofman
      ireland:
        - ireland
      sweden:
        - sweden
        - sweden2
      finland:
        - finland
      denmark:
        - denmark
      norway:
        - norway
      iceland:
        - iceland

    south:
      italy:
        - italy-naples
        - italy-cosenza
        - italy-milan
      austria:
        - austria
      greece:
        - greece
      cyprus:
        - cyprus
      malta:
        - malta
      monaco:
        - monaco

    east:
      poland:
        - poland
      lithuania:
        - lithuania
      czech_republic:
        - czechrepublic
      romania:
        - romania
      ukraine:
        - ukraine
      hungary:
        - hungary
      bulgaria:
        - bulgaria
      croatia:
        - croatia
      slovenia:
        - slovenia
      latvia:
        - latvia
      albania:
        - albania
      slovakia:
        - slovakia
      estonia:
        - estonia
      serbia:
        - serbia
      macedonia:
        - macedonia
      bosnia_and_herzegovina:
        - bosniaandherzegovina
      belarus:
        - belarus
      montenegro:
        - montenegro

###############################################
# asia
###############################################

  asia:
    east:
      japan:
        - japan-shibuya
        - japan-osaka
        - japan-yokohama
        - japan-tokyo
      hong_kong:
        - hongkong-1
        - hongkong-2
      south_korea:
        - southkorea2
      taiwan:
        - taiwan-3
      china:
        - macau

    south_east:
      singapore:
        - singapore-marinabay
        - singapore-cbd
        - singapore-jurong
        - ph-via-sing
      thailand:
        - thailand
      malaysia:
        - malaysia
      indonesia:
        - indonesia
      vietnam:
        - vietnam
      cambodia:
        - cambodia
      laos:
        - laos
      myanmar:
        - myanmar

    central:
      india:
        - india-sg
        - india-uk
      uzbekistan:
        - uzbekistan
      kazakhstan:
        - kazakhstan
      mongolia:
        - mongolia
      bangladesh:
        - bangladesh
      bhutan:
        - bhutan
      brunei:
        - brunei
      nepal:
        - nepal
      pakistan:
        - pakistan
      sri_lanka:
        - srilanka

    west:
      turkey:
        - turkey
      georgia:
        - georgia
      armenia:
        - armenia
      israel:
        - israel
      lebanon:
        - lebanon

###############################################
# oceania
###############################################

  oceania:
    main:
      australia:
        - australia-sydney
        - australia-sydney-2
        - australia-adelaide-
        - australia-melbourne
        - australia-brisbane
        - australia-perth
        - australia-woolloomooloo-2
      new_zealand:
        - newzealand

  islands:
    guam:
      - guam

###############################################
# africa
###############################################

  africa:
    north:
      egypt:
        - egypt
      algeria:
        - algeria

    south:
      south_africa:
        - southafrica

    east:
      kenya:
        - kenya

    west:
      ghana:
        - ghana
      morocco:
        - morocco

###############################################
# south america
###############################################

  south_america:
    east:
      brazil:
        - brazil
        - brazil-2

    south:
      argentina:
        - argentina
      uruguay:
        - uruguay

    west:
      chile:
        - chile
      peru:
        - peru
      bolivia:
        - bolivia

    north:
      colombia:
        - colombia
      venezuela:
        - venezuela
      ecuador:
        - ecuador
