---
ssmtp:
  email_server: smtp.gmail.com:587

deluge:
  add_paused: "false"
  completed_dir: completed
  incoming_dir: incoming
  max_active_downloading: 20
  max_active_limit: 20
  max_download_speed: 3000
  move_completed: "true"
  torrent_dir: torrents

oauth:
  client_id: oauth2-proxy

maxmind:
  rotate_after_days: 15

nginx:
  client_max_body_size: 10G

  docs:
    restricted_pages:
      - name: inventory
        group: partners,operators

      - name: pimp
        group: partners,operators,clients

      - name: raidvol
        group: partners,operators,clients

  geoip_whitelists:
    country:
      - United States

    city: [
      "Broomfield", "Superior", "Louisville", "Lafayette", "Westminster",
      "Boulder", "Federal Heights", "Northglenn", "Thornton", "Commerce City",
      "Denver", "Wheat Ridge", "Arvada", "Lakewood", "Edgewater", "Aurora"
    ]
