---
ssmtp:
  email_server: smtp.gmail.com:587

oauth:
  client_id: oauth2-proxy

maxmind:
  rotate_after_days: 15

nginx:
  client_max_body_size: 10G

  docs:
    restricted_pages:
      - name: inventory
        group: partners,operators

      - name: pimp
        group: partners,operators,clients

      - name: raidvol
        group: partners,operators,clients

  geoip_whitelists:
    general:
      countries:
        - United States

      cities: [
        "Broomfield", "Superior", "Louisville", "Lafayette", "Westminster",
        "Boulder", "Federal Heights", "Northglenn", "Thornton", "Commerce City",
        "Denver", "Wheat Ridge", "Arvada", "Lakewood", "Edgewater", "Aurora"
      ]

    plex:
      countries:
        - United States
        - Switzerland
        - Iceland
        - Panama
