---
- name: main - copy ssh key
  template:
    src: /root/ssh.key
    dest: /root/ssh.key
    owner: root
    group: root
    mode: '0600'
  become: true

- include_tasks: tunnels.yml
  with_items:
    - "{{ tunnels }}"
