---
- name: TUNNELS - copy ssh key
  ansible.builtin.copy:
    src: /root/ansible-ssh.key
    dest: /root/tunnel-ssh.key
    owner: root
    group: root
    mode: '0600'
  become: true
  when: item.host == inventory_hostname

- name: "TUNNELS - create directory for tunnel-{{ item.name }}"
  ansible.builtin.file:
    state: directory
    path: "/root/tunnel-{{ item.name }}"
    owner: root
    group: root
    mode: '0770'
  become: true
  when: item.host == inventory_hostname

- name: "TUNNELS - create script for tunnel-{{ item.name }}"
  ansible.builtin.template:
    src: tunnel.sh
    dest: "/root/tunnel-{{ item.name }}/tunnel-{{ item.name }}.sh"
    owner: root
    group: root
    mode: '0750'
  become: true
  notify: "MAIN - systemctl restart tunnel-{{ item.name }}"
  when: item.host == inventory_hostname

- name: "TUNNELS - create systemd unit for tunnel-{{ item.name }}"
  ansible.builtin.template:
    src: tunnel.service
    dest: /lib/systemd/system/tunnel-{{ item.name }}.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: "MAIN - systemctl restart tunnel-{{ item.name }}"
  when: item.host == inventory_hostname

- name: MAIN - flush handlers
  ansible.builtin.meta: flush_handlers

- name: "TUNNELS - configure service for tunnel-{{ item.name }}"
  ansible.builtin.systemd:
    name: "tunnel-{{ item.name }}"
    enabled: false
    daemon_reload: true
    state: "{{ item.state }}"
  become: true
  when: item.host == inventory_hostname
