---
- name: "TUNNELS - create script for tunnel-{{ item.name }}"
  ansible.builtin.template:
    src: tunnel.sh
    dest: "{{ folder_ssh_tunnels }}/tunnel-{{ item.name }}.sh"
    owner: "{{ names.users.host.associate.name }}"
    group: "{{ names.groups.devops.name }}"
    mode: '0740'
  become: true
  notify: "MAIN - systemctl restart tunnel-{{ item.name }}"
  when: item.host == inventory_hostname

- name: "TUNNELS - create systemd unit for tunnel-{{ item.name }}"
  ansible.builtin.template:
    src: tunnel.service
    dest: /lib/systemd/system/tunnel-{{ item.name }}.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: "MAIN - systemctl restart tunnel-{{ item.name }}"
  when: item.host == inventory_hostname

- name: MAIN - flush handlers
  ansible.builtin.meta: flush_handlers

- name: "TUNNELS - configure service for tunnel-{{ item.name }}"
  ansible.builtin.systemd:
    name: "tunnel-{{ item.name }}"
    enabled: false
    daemon_reload: true
    state: "{{ item.state }}"
  become: true
  when: item.host == inventory_hostname
