---
- name: MAIN - systemctl restart tunnel-nginx
  ansible.builtin.systemd:
    name: tunnel-nginx
    state: restarted
    daemon_reload: true
  become: true

- name: MAIN - systemctl restart tunnel-openvpnas
  ansible.builtin.systemd:
    name: tunnel-openvpnas
    state: restarted
    daemon_reload: true
  become: true

- name: MAIN - systemctl restart tunnel-gitlab
  ansible.builtin.systemd:
    name: tunnel-gitlab
    state: restarted
    daemon_reload: true
  become: true
