---
cifs_globals: "uid=0,gid={{ names.raid_vol.group.gid }},dir_mode=0770,file_mode=0660"

mounts:
  samba:
    - host: "{{ names.hosts.docker02 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.raid_vol }}"
      src: "//{{ nas_vlan_20_address }}/{{ names.raid_vol.name }}-documents"
      path: "/mnt/{{ names.raid_vol.name }}-documents"
      username: "{{ names.lab_users.raid_vol.documents_ro }}"
      password: "{{ secrets.lab_users.nas.raid_vol.documents_ro }}"

    - host: "{{ names.hosts.docker02 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.raid_vol }}"
      src: "//{{ nas_vlan_20_address }}/{{ names.raid_vol.name }}-music"
      path: "/mnt/{{ names.raid_vol.name }}-music"
      username: "{{ names.lab_users.raid_vol.music_ro }}"
      password: "{{ secrets.lab_users.nas.raid_vol.music_ro }}"

    - host: "{{ names.hosts.docker02 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.raid_vol }}"
      src: "//{{ nas_vlan_20_address }}/{{ names.raid_vol.name }}-pictures"
      path: "/mnt/{{ names.raid_vol.name }}-pictures"
      username: "{{ names.lab_users.raid_vol.pictures_ro }}"
      password: "{{ secrets.lab_users.nas.raid_vol.pictures_ro }}"

    - host: "{{ names.hosts.docker02 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.raid_vol }}"
      src: "//{{ nas_vlan_20_address }}/{{ names.raid_vol.name }}-plex_libraries"
      path: "/mnt/{{ names.raid_vol.name }}-plex_libraries"
      username: "{{ names.lab_users.raid_vol.plex_libraries_rw }}"
      password: "{{ secrets.lab_users.nas.raid_vol.plex_libraries_rw }}"

    - host: "{{ names.hosts.docker01 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.raid_vol }}"
      src: "//{{ nas_vlan_20_address }}/{{ names.raid_vol.name }}-plex_libraries"
      path: "/mnt/{{ names.raid_vol.name }}-plex_libraries"
      username: "{{ names.lab_users.raid_vol.plex_libraries_ro }}"
      password: "{{ secrets.lab_users.nas.raid_vol.plex_libraries_ro }}"

    - host: "{{ names.hosts.docker01 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.raid_vol }}"
      src: "//{{ nas_vlan_20_address }}/{{ names.raid_vol.name }}-deluge"
      path: "/mnt/{{ names.raid_vol.name }}-deluge"
      username: "{{ names.lab_users.raid_vol.deluge_rw }}"
      password: "{{ secrets.lab_users.nas.raid_vol.deluge_rw }}"

    - host: "{{ names.hosts.docker02 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.raid_vol }}"
      src: "//{{ nas_vlan_20_address }}/{{ names.raid_vol.name }}-deluge"
      path: "/mnt/{{ names.raid_vol.name }}-deluge"
      username: "{{ names.lab_users.raid_vol.deluge_rw }}"
      password: "{{ secrets.lab_users.nas.raid_vol.deluge_rw }}"

    - host: "{{ names.hosts.docker02 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.raid_vol }}"
      src: "//{{ nas_vlan_20_address }}/{{ names.raid_vol.name }}-tfstate"
      path: "/mnt/{{ names.raid_vol.name }}-tfstate"
      username: "{{ names.lab_users.raid_vol.tfstate_rw }}"
      password: "{{ secrets.lab_users.nas.raid_vol.tfstate_rw }}"

  glusterfs:
    - host: "{{ names.hosts.docker01 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.dfs_lvm }}"
      src: /dev/mapper/ubuntu--vg-dfs_lvm
      path: /mnt/dfs_lvm

    - host: "{{ names.hosts.docker02 }}.{{ lab.domain }}"
      state: "{{ cycle_mode.volumes.dfs_lvm }}"
      src: /dev/mapper/ubuntu--vg-dfs_lvm
      path: /mnt/dfs_lvm
