---
- name: MAIN - add apt repository key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    owner: root
    group: root
    mode: '0644'
  become: true

- name: MAIN - add docker apt repository
  ansible.builtin.copy:
    content: deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu/ {{ ansible_lsb.codename }} stable
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0644'
  become: true

- name: MAIN - install docker packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - "{{ docker.ubuntu_packages }}"

- name: MAIN - create local .docker directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.docker"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: MAIN - manage local docker configuration
  ansible.builtin.template:
    src: config.json
    dest: /home/{{ ansible_user }}/.docker/config.json
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: MAIN - manage docker configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  become: true
  notify: MAIN - systemctl restart docker
  with_items:
    - src: docker.service
      dest: /lib/systemd/system/docker.service
      owner: root
      group: root
      mode: '0644'

    - src: daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'

- name: MAIN - flush handlers
  ansible.builtin.meta: flush_handlers

- name: MAIN - ensure docker daemon
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: MAIN - add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true
