---
- name: GIT - discover gitlab
  ansible.builtin.uri:
    url: "https://gitlab.{{ assignments.nginx.networking.teine.fqdn }}"
    status_code:
      - 200
      - 502
      - -1
  register: discovered_gitlab

- name: GIT - download git project
  ansible.builtin.git:
    repo: "https://{{ gitlab_credential }}@gitlab.{{ assignments.nginx.networking.teine.fqdn }}/elise/{{ item }}.git"
    dest: "/home/{{ ansible_user }}/{{ item.split('/')[-1] }}"
    update: true
    version: main
    force: true
  when: discovered_gitlab.status == 200
