---
- name: GIT - include discover tasks
  ansible.builtin.include_tasks: discover.yml

- name: "GIT - download git project - elise/{{ item.project.path }}"
  ansible.builtin.git:
    repo: "https://{{ gitlab_credential }}@gitlab.{{ assignments.nginx.networking.teine.fqdn }}/elise/{{ item.project.path }}.git"
    dest: "{{ ansible_user_dir }}/{{ item.project.path.split('/')[-1] }}"
    update: true
    version: "{{ item.project.branch }}"
    force: true
  when: discovered_gitlab.status == 200

- name: "GIT - download image - {{ item.image.name }}"
  community.docker.docker_image:
    name: "nexus-hosted.{{ assignments.nginx.networking.teine.fqdn }}/elise/{{ item.image.name }}"
    tag: "{{ item.image.tag }}"
    source: pull
  when: discovered_nexus.status == 200
