---
- name: MAIN - include pi tasks
  ansible.builtin.include_tasks: pi.yml
  when: ansible_architecture == "aarch64"

- name: MAIN - include git tasks
  ansible.builtin.include_tasks: git.yml
  vars:
    gitlab_credential: "{{ secrets.gitlab.root.username }}:{{ secrets.gitlab.root.password | urlencode }}"
  when: ansible_architecture == "aarch64" and lazarus_node is defined
  with_items:
    - project:
        path: infrastructure/iac-configure
        branch: main
      image:
        name: iac-configure
        tag: main
