---
tunnels:
  - name: nginx
    description: web ingress tunnel
    state: "{{ execute_mode.state.tunnels }}"
    host: "{{ assignments.nginx.networking.teine.fqdn }}"
    ipv4: "{{ assignments.nginx.networking.teine.ipv4 }}"
    external_port: "{{ external_ports.nginx_web }}"
    internal_port: "443"

  - name: openvpnas
    description: openvpnas tunnel
    state: "{{ execute_mode.state.tunnels }}"
    host: "{{ assignments.openvpnas.networking.teine.fqdn }}"
    ipv4: "{{ assignments.openvpnas.networking.teine.ipv4 }}"
    external_port: "1194"
    internal_port: "{{ external_ports.openvpnas_vpn }}"

  - name: elasticsearch
    description: elasticsearch tunnel
    state: "{{ execute_mode.state.tunnels }}"
    host: "{{ assignments.elasticsearch.networking.teine.fqdn }}"
    ipv4: "{{ assignments.elasticsearch.networking.teine.ipv4 }}"
    external_port: "{{ external_ports.elasticsearch_db }}"
    internal_port: "{{ external_ports.elasticsearch_db }}"

  - name: kibana
    description: kibana tunnel
    state: "{{ execute_mode.state.tunnels }}"
    host: "{{ assignments.kibana.networking.teine.fqdn }}"
    ipv4: "{{ assignments.kibana.networking.teine.ipv4 }}"
    external_port: "{{ external_ports.kibana_web }}"
    internal_port: "{{ external_ports.kibana_web }}"
