---
tunnels:
  - name: nginx
    description: web ingress tunnel
    state: "{{ cycle_mode.state.tunnels }}"
    host: "{{ assignments.nginx.networking.teine.fqdn }}"
    ipv4: "{{ assignments.nginx.networking.teine.ipv4 }}"
    external_port: "{{ external_ports.nginx_web }}"
    internal_port: "443"

  - name: openvpnas
    description: openvpnas tunnel
    state: "{{ cycle_mode.state.tunnels }}"
    host: "{{ assignments.openvpnas.networking.teine.fqdn }}"
    ipv4: "{{ assignments.openvpnas.networking.teine.ipv4 }}"
    external_port: "1194"
    internal_port: "{{ external_ports.openvpnas_vpn }}"
