---
tunnels:
  - name: nginx
    description: web ingress tunnel
    state: "{{ cycle_mode.state.tunnels }}"
    host: "{{ assignments.nginx.host }}"
    ipv4: "{{ nginx_vlan_40_address }}"
    external_port: "{{ ports.nginx_web }}"
    internal_port: "443"

  - name: openvpnas
    description: openvpnas tunnel
    state: "{{ cycle_mode.state.tunnels }}"
    host: "{{ assignments.openvpnas.host }}"
    ipv4: "{{ openvpnas_vlan_40_address }}"
    external_port: "1194"
    internal_port: "{{ ports.openvpnas_vpn }}"
