---
- name: MAIN - systemctl restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
  become: true

- name: MAIN - systemctl restart metricbeat
  ansible.builtin.systemd:
    name: metricbeat
    state: restarted
  become: true
