---
beats:
  refresh_interval: 30s
  download_url: https://artifacts.elastic.co/downloads/beats
  packages:
    - name: filebeat
      package_state: present
      service_state: "{{ cycle_mode.state.beats }}"

    - name: metricbeat
      package_state: present
      service_state: "{{ cycle_mode.state.beats }}"
