---
beats:
  version: 8.13.3
  refresh_interval: 30s
  download_url: https://artifacts.elastic.co/downloads/beats
  packages:
    - name: filebeat
      package_state: present
      service_state: "{{ execute_mode.state.beats }}"

    - name: metricbeat
      package_state: present
      service_state: "{{ execute_mode.state.beats }}"
