---
ssh:
  authorized_keys:
    - state: present
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCw5PQecme+/WsJYSh0bjEiawr\
           snIwvxZe7QWuCMdDUJgYNwz0yR3IdVlPBd1gf+PCD3qz9SkwTpGsoyYHptjjUw/\
           TYRvEEQaC2x5OwZIuprcTFYztGvDDmEX5giZdNy6Aq9uGrtnzQZRd2T8JSLi/5j\
           LJ7HWz/b1IO2puj4g/E++njPeP4Hh0FI5SPgUzdLP0GHPCAXvZXz3O9QS9kbZ28\
           ICZ4OVjTy2WBaHsfz5XLZ4mdjZIJKp1j2zyPe3WGUhYKOpoA1clk6T7ZPGZDwRU\
           AZDHB4A8HZHepmAwVsHATad/Jq4PfBHzsB4DhNrp7vez5C/51WI+jJJBvkQqALx\
           gti6D12770WCHKfxD5kFR4xzSZoXEt6RZ2oz+7wb+F5HXGGDsufP7rCDsAHU3ci\
           u8riV5J8dRY/PwQEUO5YMwxQAEIStrThDJxh3TIU2dou9u3yKdsWA8ZWULe7uJj\
           5uR0x2SLNX1H7jnZJwBeasPFSfaGPifkJNkAzuFLKsY9shMSLmLaLfgQ4vZtFyb\
           oAVvVZfMw1I5wKGhBCT5PJJ4VwuO1YX8gz7GWwc+FD/omwX6uH3LMMaCb9RKMcE\
           TXw1aB1CXEA1t3qSkIQ/G7jSdDKlPZiIvPJOGeFRZTwepvtdoBYL2kmx/UcS3BF\
           ZxXkdKN8C+p9/vg+sX9A+WE1BaBTw== austin@elysianskies.com
