---
build_docker_ansible:
  stage: integrate
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - ansible/*
        - ansible/*/*
        - ansible/*/*/*
        - ansible/*/*/*/*
        - ansible/*/*/*/*/*
        - Dockerfile
        - ssh.key
  needs:
    - secret_detection
  script:
    - |
      DOCKER_BUILDKIT=1 docker build . \
          --tag "$ELISE_CI_NEXUS_HOSTED/elise/elysianskies-configure:$CI_COMMIT_REF_SLUG"
    - docker push "$ELISE_CI_NEXUS_HOSTED/elise/elysianskies-configure:$CI_COMMIT_REF_SLUG"
