---
- name: MAIN - docker restart elasticsearch
  ansible.builtin.command: |
    /bin/bash -c "
      if [ ! -z \"$(docker ps --quiet --filter status=running --filter name=elasticsearch)\" ]; then
        docker restart elasticsearch
      fi
    "
  become: true
  when: inventory_hostname == assignments.elasticsearch.host
  changed_when: false

- name: MAIN - docker restart filebrowser
  ansible.builtin.command: |
    /bin/bash -c "
      if [ ! -z \"$(docker ps --quiet --filter status=running --filter name=filebrowser)\" ]; then
        docker restart filebrowser
      fi
    "
  become: true
  when: inventory_hostname == assignments.filebrowser.host
  changed_when: false

- name: MAIN - docker restart kibana
  ansible.builtin.command: |
    /bin/bash -c "
      if [ ! -z \"$(docker ps --quiet --filter status=running --filter name=kibana)\" ]; then
        docker restart kibana
      fi
    "
  become: true
  when: inventory_hostname == assignments.kibana.host
  changed_when: false

- name: MAIN - docker restart nginx
  ansible.builtin.command: |
    /bin/bash -c "
      if [ ! -z \"$(docker ps --quiet --filter status=running --filter name=nginx)\" ]; then
        echo '{{ secrets.users.host.iac[inventory_hostname] }}' | sudo -S systemctl stop tunnel-nginx
        docker restart nginx
        echo '{{ secrets.users.host.iac[inventory_hostname] }}' | sudo -S systemctl start tunnel-nginx
      fi
    "
  no_log: true
  become: true
  when: inventory_hostname == assignments.nginx.host
  changed_when: false

- name: MAIN - docker restart oauth
  ansible.builtin.command: |
    /bin/bash -c "
      if [ ! -z \"$(docker ps --quiet --filter status=running --filter name=oauth)\" ]; then
        docker restart oauth
      fi
    "
  become: true
  when: inventory_hostname == assignments.oauth.host
  changed_when: false

- name: MAIN - docker restart vault
  ansible.builtin.command: |
    /bin/bash -c "
      if [ ! -z \"$(docker ps --quiet --filter status=running --filter name=vault)\" ]; then
        docker restart vault
      fi
    "
  become: true
  when: inventory_hostname == assignments.vault.host
  changed_when: false

- name: MAIN - docker restart zoneminder
  ansible.builtin.command: |
    /bin/bash -c "
      if [ ! -z \"$(docker ps --quiet --filter status=running --filter name=zoneminder)\" ]; then
        docker restart zoneminder
      fi
    "
  become: true
  when: inventory_hostname == assignments.zoneminder.host
  changed_when: false
