---
- name: CONTAINERS - apply elise.containers role
  hosts: localhost
  roles:
    - elise.containers
  vars_files:
    - group_vars/all/secrets.yml

- name: CONTAINERS - apply docker prune
  hosts: lab_onprem_docker
  vars_files:
    - group_vars/all/secrets.yml
  tasks:
    - name: CONTAINERS - prune unused docker resources
      community.docker.docker_prune:
        containers: true
        containers_filters:
          "label!": lab_container=true
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true
      when: lookup('env', 'ELISE_PROJECT_CRON_TRIGGER') == "true"
      become: true
