---
- name: CONTAINERS - apply elise.containers role
  hosts: localhost
  roles:
    - elise.containers
  vars_files:
    - group_vars/concats.yml
    - group_vars/lab.yml
    - group_vars/ports.yml
    - group_vars/secrets.yml
