---
- name: DEPLOY - import up playbook
  import_playbook: up.yml

- name: DEPLOY - import general playbook
  import_playbook: general.yml

- name: DEPLOY - import elysianskies playbook
  import_playbook: elysianskies.yml

- name: DEPLOY - import runner playbook
  import_playbook: runner.yml

- name: DEPLOY - import portal playbook
  import_playbook: portal.yml

- name: DEPLOY - import tunnels playbook
  import_playbook: tunnels.yml

- name: DEPLOY - import beats playbook
  import_playbook: beats.yml
