---
- name: DESTROY - import beats playbook
  import_playbook: beats.yml

- name: DESTROY - import tunnels playbook
  import_playbook: tunnels.yml

- name: DESTROY - import portal playbook
  import_playbook: portal.yml

- name: DESTROY - import runner playbook
  import_playbook: runner.yml

- name: DESTROY - import elysianskies playbook
  import_playbook: elysianskies.yml

- name: DESTROY - import general playbook
  import_playbook: general.yml

- name: DESTROY - import down playbook
  import_playbook: down.yml
