---
- name: DESTROY - gather facts
  hosts: all
  gather_facts: true

- name: DESTROY - import beats playbook
  import_playbook: beats.yml

- name: DESTROY - import tunnels playbook
  import_playbook: tunnels.yml

- name: DESTROY - import portal playbook
  import_playbook: portal.yml

- name: DESTROY - import containers playbook
  import_playbook: containers.yml

- name: DESTROY - import glusterfs playbook
  import_playbook: glusterfs.yml

- name: DESTROY - import mounts playbook
  import_playbook: mounts.yml

- name: DESTROY - import ubuntu playbook
  import_playbook: ubuntu.yml

- name: DESTROY - import down playbook
  import_playbook: down.yml
