---
- name: DOWN - run connectivity task
  hosts: all
  tasks:
    - name: SITE - determine internet connectivity
      ansible.builtin.uri:
        url: "https://www.google.com"
        status_code:
          - -1
          - 200
          - 429
      register: internet_check

- name: DOWN - import tfstate playbook
  import_playbook: tfstate.yml

- name: DOWN - gather facts
  hosts: all
  gather_facts: true

- name: DOWN - import beats playbook
  import_playbook: beats.yml

- name: DOWN - import tunnels playbook
  import_playbook: tunnels.yml

- name: DOWN - import portal playbook
  import_playbook: portal.yml

- name: DOWN - import containers playbook
  import_playbook: containers.yml

- name: DOWN - import glusterfs playbook
  import_playbook: glusterfs.yml

- name: DOWN - import mounts playbook
  import_playbook: mounts.yml

- name: DOWN - import ubuntu playbook
  import_playbook: ubuntu.yml

- name: UP - import linode playbook
  import_playbook: linode.yml

- name: DOWN - import poweroff playbook
  import_playbook: poweroff.yml
