---
- name: ELYSIANSKIES - apply elise.mounts, elise.glusterfs, elise.docker, and elise.configs roles
  hosts: elysianskies_onprem_docker
  gather_facts: true
  roles:
    - elise.mounts
    - elise.glusterfs
    - elise.docker
    - elise.configs

- name: ELYSIANSKIES - apply elise.containers role
  hosts: localhost
  roles:
    - elise.containers
  vars_files:
    - group_vars/all.yml
    - group_vars/secrets.yml
    - group_vars/elysianskies_onprem_docker.yml
