---
- name: SHUTDOWN - import beats playbook
  import_playbook: beats.yml

- name: SHUTDOWN - import tunnels playbook
  import_playbook: tunnels.yml

- name: SHUTDOWN - import portal playbook
  import_playbook: portal.yml

- name: SHUTDOWN - import runner playbook
  import_playbook: runner.yml

- name: SHUTDOWN - import elysianskies playbook
  import_playbook: elysianskies.yml

- name: SHUTDOWN - import general playbook
  import_playbook: general.yml
