---
- name: SITE - import deploy playbook
  import_playbook: deploy.yml
  vars:
    execute_mode: "{{ execute_modes.deploy }}"
  when: lookup('env', 'PLAYBOOK_SITE_MODE') == "deploy"

- name: SITE - import shutdown playbook
  import_playbook: shutdown.yml
  vars:
    execute_mode: "{{ execute_modes.shutdown }}"
  when: lookup('env', 'PLAYBOOK_SITE_MODE') == "shutdown"

- name: SITE - import destroy playbook
  import_playbook: destroy.yml
  vars:
    execute_mode: "{{ execute_modes.destroy }}"
  when: lookup('env', 'PLAYBOOK_SITE_MODE') == "destroy"
