---
- name: UP - import secrets playbook
  import_playbook: secrets.yml
  vars:
    secrets_mode: start

# - {name: UP - import wake playbook, import_playbook: wake.yml}
- {name: UP - import terraform playbook, import_playbook: terraform.yml}
# - {name: UP - import linode playbook, import_playbook: linode.yml}

- name: UP - gather facts
  hosts: all
  gather_facts: true
  gather_timeout: 60
  vars_files:
    - group_vars/all/secrets.yml

# - {name: UP - import hosts playbook, import_playbook: hosts.yml}
- {name: UP - import entities playbook, import_playbook: entities.yml}
# - {name: UP - import sudoers playbook, import_playbook: sudoers.yml}
# - {name: UP - import init playbook, import_playbook: init.yml}
# - {name: UP - import ubuntu playbook, import_playbook: ubuntu.yml}
# - {name: UP - import raspberrypi playbook, import_playbook: raspberrypi.yml}
# - {name: UP - import mounts playbook, import_playbook: mounts.yml}
# - {name: UP - import glusterfs playbook, import_playbook: glusterfs.yml}
# - {name: UP - import docker playbook, import_playbook: docker.yml}
# - {name: UP - import configs playbook, import_playbook: configs.yml}
# - {name: UP - import containers playbook, import_playbook: containers.yml}
# - {name: UP - import runner playbook, import_playbook: runner.yml}
# - {name: UP - import portal playbook, import_playbook: portal.yml}
# - {name: UP - import tunnels playbook, import_playbook: tunnels.yml}
# - {name: UP - import beats playbook, import_playbook: beats.yml}

- name: UP - import secrets playbook
  import_playbook: secrets.yml
  vars:
    secrets_mode: stop
