---
- name: UP - import secrets playbook
  import_playbook: secrets.yml
  vars:
    secrets_mode: start

- {name: UP - import wake playbook, import_playbook: wake.yml}
- {name: UP - import linode playbook, import_playbook: linode.yml}

- name: UP - gather facts
  hosts: all
  gather_facts: true
  gather_timeout: 60
  vars_files:
    - group_vars/all/secrets.yml

- {name: UP - import sudoers playbook, import_playbook: sudoers.yml}
- {name: UP - import mounts playbook, import_playbook: mounts.yml}
- {name: UP - import glusterfs playbook, import_playbook: glusterfs.yml}
- {name: UP - import containers playbook, import_playbook: containers.yml}
- {name: UP - import portal playbook, import_playbook: portal.yml}
- {name: UP - import tunnels playbook, import_playbook: tunnels.yml}
- {name: UP - import beats playbook, import_playbook: beats.yml}

- name: UP - import secrets playbook
  import_playbook: secrets.yml
  vars:
    secrets_mode: stop
