---
- name: VOLUMES - apply elise.volumes role
  hosts: localhost
  roles:
    - elise.volumes
  vars_files:
    - group_vars/concats.yml
    - group_vars/lab.yml
    - group_vars/names.yml
    - group_vars/ports.yml
    - group_vars/secrets.yml
