---
- name: LINODE - fetch elysianskies tfstate
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.file', '/tfstate/elysianskies.json') }}"
  no_log: true
  register: elysianskies_tfstate

- name: LINODE - create linode ip address files
  delegate_to: localhost
  ansible.builtin.template:
    src: linode-ipv4.txt
    dest: "/tfstate/{{ item.output_elements.ip_address }}.txt"
    mode: '0644'
  changed_when: false
  with_items:
    - "{{ linodes }}"

- name: LINODE - include wake tasks
  ansible.builtin.include_tasks: wake.yml
  with_items:
    - "{{ linodes }}"
