---
- name: MAIN - include discover tasks
  ansible.builtin.include_tasks: discover.yml

- name: MAIN - manage linode
  linode_state:
    token: "{{ secrets.external.linode.token }}"
    label_prefix: "{{ lab.domain | regex_replace('.com$', '') }}-portal"
    state: "{{ 'restarted' if external_check.status == 200
      and internal_check.status != 200
      and ( cycle_mode.name == 'full' or cycle_mode.name == 'up' )
      else cycle_mode.state.portal.linode
      }}"
  when: internet_found == "yes"

- name: MAIN - waiting on host port 22
  ansible.builtin.wait_for:
    host: "portal.{{ lab.domain }}"
    state: "{{ cycle_mode.state.portal.linode }}"
    port: 22
  when: internet_found == "yes"
