---
- name: LINODE - fetch elysianskies tfstate
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.file', '/tfstate/elysianskies.json') }}"
  no_log: true
  register: elysianskies_tfstate

- name: LINODE - create linode ip address files
  ansible.builtin.copy:
    content: "{{ elysianskies_tfstate.msg.outputs[item.output_elements.ip_address].value[0] }}"
    dest: "/tfstate/{{ item.output_elements.ip_address }}.txt"
    mode: '0644'
  changed_when: false
  with_items:
    - "{{ linodes }}"

- name: LINODE - confirm connectivity to the internet
  ansible.builtin.wait_for:
    host: 8.8.8.8
    port: 443
    state: started
    delay: 5

- name: LINODE - include wake tasks
  ansible.builtin.include_tasks: wake.yml
  with_items:
    - "{{ linodes }}"
