---
- name: WAKE - manage linode
  linode_state:
    token: "{{ lookup('env', 'LINODE_TOKEN') }}"
    id: "{{ elysianskies_tfstate.msg.outputs[item.output_elements.instance_id].value[0] }}"
    state: "{{ item.state }}"

- name: "WAKE - waiting on host port {{ item.wait_port }}"
  ansible.builtin.wait_for:
    host: "{{ elysianskies_tfstate.msg.outputs[item.output_elements.ip_address].value[0] }}"
    port: "{{ item.wait_port }}"
    state: "{{ item.state }}"
