---
- name: WAKE - determine external nginx connectivity
  ansible.builtin.uri:
    url: "https://ping.home.elysianskies.com"
    status_code:
      - -1
      - 200
      - 502
  register: external_check

- name: WAKE - determine internal nginx connectivity
  ansible.builtin.uri:
    url: "https://ping.docker02-teine.home.elysianskies.com"
    status_code:
      - -1
      - 200
      - 502
  register: internal_check

- name: WAKE - manage linode
  linode_state:
    token: "{{ secrets.linode.token }}"
    id: "{{ elysianskies_tfstate.msg.outputs[item.output_elements.instance_id].value[0] }}"
    state: "{{ 'restarted' if external_check.status == 200 and internal_check.status != 200 and cycle_mode.name == 'up' else item.state }}"
  when: internet_check.status == 200

- name: "WAKE - waiting on host port {{ item.wait_port }}"
  ansible.builtin.wait_for:
    host: "{{ elysianskies_tfstate.msg.outputs[item.output_elements.ip_address].value[0] }}"
    port: "{{ item.wait_port }}"
    state: "{{ item.state }}"
  when: internet_check.status == 200
