---
- name: BACKUP - copy secrets to persisted host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/group_vars/all/secrets.yml"
    dest: "/home/{{ names.users.host.iac }}/secrets.yml"
    owner: "{{ names.users.host.iac }}"
    group: "{{ names.users.host.iac }}"
    mode: "0600"
    decrypt: false
  vars:
    secrets:
      users:
        host:
          iac:
            docker00: ""
  delegate_to: "{{ vault.persisted_host }}"

- name: BACKUP - remove local secrets
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ playbook_dir }}/group_vars/all/secrets.yml"
