---
- name: CLEAN - remove secrets from persisted host
  ansible.builtin.file:
    path: "{{ vault.persisted_host.path }}"
    state: absent
  vars:
    secrets:
      users:
        docker00:
          privileged: ""
  delegate_to: "{{ vault.persisted_host.name }}"

- name: CLEAN - remove local secrets
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  changed_when: false
  with_items:
    - "{{ playbook_dir }}/group_vars/all/secrets.yml"
