---
- name: CLEAN - remove secrets from persisted host
  ansible.builtin.file:
    dest: "{{ folder_automation }}/secrets.yml"
    state: absent
  vars:
    secrets:
      users:
        host:
          iac:
            docker00: ""
  delegate_to: "{{ vault.persisted_host }}"

- name: CLEAN - remove local secrets
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  changed_when: false
  with_items:
    - "{{ playbook_dir }}/group_vars/all/secrets.yml"
