---
- name: MAIN - find vault
  ansible.builtin.uri:
    url: "http://{{ vault.ipv4 }}:{{ ports.vault_web }}"
    status_code: "{{ lab.task_globals.discover_uri.status_code }}"
  register: vault_check

- name: MAIN - include persist tasks
  ansible.builtin.include_tasks: persist.yml
  when: vault_check.status != 200 and ( cycle_mode.name == "full" or cycle_mode.name == "up" ) and secrets_mode == "start"

- name: MAIN - include clean tasks
  ansible.builtin.include_tasks: clean.yml
  when: vault_check.status == 200 and ( cycle_mode.name == "full" or cycle_mode.name == "up" ) and secrets_mode == "stop"

- name: MAIN - include vault tasks
  ansible.builtin.include_tasks: vault.yml
  when: vault_check.status == 200 and ( cycle_mode.name == "full" or cycle_mode.name == "up" ) and secrets_mode == "start"

- name: MAIN - include vault tasks
  ansible.builtin.include_tasks: vault.yml
  when: vault_check.status == 200 and cycle_mode.name == "down" and secrets_mode == "start"

- name: MAIN - include backup tasks
  ansible.builtin.include_tasks: backup.yml
  when: vault_check.status != 200 and cycle_mode.name == "down" and secrets_mode == "stop"
