---
- name: PERSIST - retrieve secrets from persisted host
  ansible.builtin.fetch:
    src: "{{ folder_automation }}/secrets.yml"
    dest: "{{ playbook_dir }}/group_vars/all/secrets.yml"
    flat: true
  vars:
    secrets:
      users:
        host:
          iac:
            docker00: ""
  delegate_to: "{{ vault.persisted_host }}"
  changed_when: false
