---
- name: GATEWAY - enable modprobe iptable_nat
  community.general.modprobe:
    name: iptable_nat
    state: present
  become: true

- name: GATEWAY - masquerade postrouting chain for external interface
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ gateway.external_interface }}"
    jump: MASQUERADE
    state: "{{ cycle_mode.gateway_masquerade }}"
  become: true

- name: GATEWAY - accept internal interface on forward chain
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    in_interface: "{{ gateway.internal_interface }}"
    jump: ACCEPT
    state: "{{ cycle_mode.gateway_masquerade }}"
  become: true

- name: GATEWAY - accept internal interface and external interface on forward chain
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    in_interface: "{{ gateway.internal_interface }}"
    out_interface: "{{ gateway.external_interface }}"
    jump: ACCEPT
    state: "{{ cycle_mode.gateway_masquerade }}"
  become: true

- name: GATEWAY - accept internal interface and external interface on return forward chain
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    in_interface: "{{ gateway.external_interface }}"
    out_interface: "{{ gateway.internal_interface }}"
    match:
      - state
    ctstate:
      - RELATED
      - ESTABLISHED
    jump: ACCEPT
    state: "{{ cycle_mode.gateway_masquerade }}"
  become: true
