---
lab_filesystem:
  - path: "{{ folder_root }}"
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.groups.devops.name }}"
    mode: "0750"

  - path: "{{ folder_automation }}"
    owner: "{{ names.users.host.iac.name }}"
    group: "{{ names.users.host.iac.name }}"
    mode: "0750"

  - path: "{{ folder_container }}"
    owner: "{{ names.users.host.iac.name }}"
    group: "{{ names.users.host.engineer.name }}"
    mode: "0750"

  - path: "{{ folder_container_app }}"
    owner: root
    group: "{{ names.groups.devops.name }}"
    mode: "0750"

  - path: "{{ folder_container_config }}"
    owner: root
    group: "{{ names.groups.devops.name }}"
    mode: "0750"

  - path: "{{ folder_secrets }}"
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.users.host.admin.name }}"
    mode: "0700"

  - path: "{{ folder_secrets_approle }}"
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.users.host.admin.name }}"
    mode: "0700"

  - path: "{{ folder_secrets_automation }}"
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.users.host.admin.name }}"
    mode: "0700"

  - path: "{{ folder_secrets_docker }}"
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.users.host.admin.name }}"
    mode: "0700"

  - path: "{{ folder_secrets_raid }}"
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.users.host.admin.name }}"
    mode: "0700"

  - path: "{{ folder_ssh_tunnels }}"
    owner: "{{ names.users.host.iac.name }}"
    group: "{{ names.groups.devops.name }}"
    mode: "0750"

  - path: "{{ folder_raid }}"
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.groups.raid.name }}"
    mode: "0770"

  - path: "{{ folder_raid_grail }}"
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.users.host.admin.name }}"
    mode: "0700"
