---
- name: MOUNT - mount glusterfs volume
  ansible.posix.mount:
    fstype: glusterfs
    src: "{{ ansible_facts[lan_ints.vlan_20].ipv4.address }}:{{ glusterfs.dfs.name }}"
    opts: defaults
    path: "{{ folder_container_app }}"
    state: "{{ glusterfs.mount.state }}"
  become: true
