---
- name: MOUNT - ensure app_data directory
  ansible.builtin.file:
    path: "{{ lab.dirs.app_data }}"
    state: directory
    owner: "{{ lab.dirs.owner }}"
    group: "{{ lab.dirs.group }}"
    mode: "{{ lab.dirs.mode }}"
  become: true

- name: MOUNT - mount glusterfs volume
  ansible.posix.mount:
    fstype: glusterfs
    src: "{{ ansible_facts[lan_ints.vlan_20].ipv4.address }}:{{ glusterfs.dfs.name }}"
    opts: defaults
    path: "{{ lab.dirs.app_data }}"
    state: "{{ glusterfs.mount.state }}"
  become: true
