---
- name: MOUNT - ensure glusterfs mount path
  ansible.builtin.file:
    path: "{{ glusterfs.dfs.path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: MOUNT - mount glusterfs volume
  ansible.posix.mount:
    fstype: glusterfs
    src: "{{ ansible_facts[lan_interface.uisge].ipv4.address }}:{{ glusterfs.dfs.name }}"
    opts: defaults
    path: "{{ glusterfs.dfs.path }}"
    state: "{{ glusterfs.mount.state }}"
  become: true
