---
runner:
  url: "http://{{ gitlab_vlan_40_address }}:{{ ports.gitlab_web }}"
  clone_url: "http://{{ gitlab_vlan_40_address }}:{{ ports.gitlab_web }}"
  executor: docker
  docker_image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_proxy }}/docker:28-dind"
  description: lab_runner
  docker_privileged: "true"
  docker_volumes:
    - "{{ folder_secrets_approle }}:/approle:ro"
    - "{{ folder_secrets_automation }}:/automation:ro"
    - "{{ folder_secrets_docker }}:/root/.docker:rw"
    - "{{ folder_raid }}/{{ names.raid }}-green_rw:/tfstate:rw"
    - /var/run/docker.sock:/var/run/docker.sock:rw
