---
runner:
  url: "http://{{ gitlab_vlan_40_address }}:{{ ports.gitlab_web }}"
  clone_url: "http://{{ gitlab_vlan_40_address }}:{{ ports.gitlab_web }}"
  executor: docker
  docker_image: "{{ nexus_vlan_40_address }}:{{ ports.nexus_docker_proxy }}/docker:28-dind"
  description: lab_runner
  docker_privileged: "true"
  docker_volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /root/.docker:/root/.docker:rw
    - "/mnt/{{ names.raid_vol.name }}-tfstate:/tfstate:rw"
    - "/mnt/{{ names.raid_vol.name }}-plex_libraries:/plex_libraries:rw"
