---
runner:
  url: "http://{{ assignments.gitlab.networking.teine.ipv4 }}:{{ external_ports.gitlab_web }}"
  clone_url: "http://{{ assignments.gitlab.networking.teine.ipv4 }}:{{ external_ports.gitlab_web }}"
  executor: docker
  docker_image: docker:20-dind
  description: elysianskies_runner
  tag_list: elysianskies_runner
  docker_privileged: "true"
  run_untagged: "false"
  docker_volume_1: /cache
  docker_volume_2: /var/run/docker.sock:/var/run/docker.sock:rw
  docker_volume_3: /home/{{ ansible_user }}/.docker/config.json:/root/.docker/config.json:rw
