---
ubuntu:
  apt:
    mirror_proxy: "http://{{ assignments.nexus.networking.teine.ipv4 }}:{{ external_ports.nexus_web }}/repository/elysianskies_apt_proxy/"
    mirror_original: http://us.archive.ubuntu.com/ubuntu/
    distro: jammy
  additional_packages:
    - name: net-tools
      state: present

    - name: dnsutils
      state: present

    - name: htop
      state: present

    - name: software-properties-common
      state: present

    - name: jq
      state: present

    - name: autossh
      state: present

    - name: cifs-utils
      state: present

gateway:
  internal_interface: enp1s0f0
  external_interface: enp1s0f1
