---
- name: BEATS - download packages
  ansible.builtin.uri:
    url: "{{ beats.download_url }}/{{ item.name }}/{{ item.name }}-{{ beats.version }}-amd64.deb"
    method: GET
    dest: "/tmp/{{ item.name }}-{{ beats.version }}-amd64.deb"
    status_code:
      - 200
      - 304

- name: BEATS - install packages
  ansible.builtin.apt:
    deb: "/tmp/{{ item.name }}-{{ beats.version }}-amd64.deb"
    state: "{{ item.package_state }}"
    update_cache: true
  become: true

- name: BEATS - copy templates
  ansible.builtin.template:
    src: "{{ item.name }}.yml"
    dest: "/etc/{{ item.name }}/{{ item.name }}.yml"
    owner: root
    group: root
    mode: '0755'
  become: true
  notify: "MAIN - systemctl restart {{ item.name }}"

- name: BEATS - flush handlers
  ansible.builtin.meta: flush_handlers

- name: BEATS - ensure daemon
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    state: "{{ item.service_state }}"
    enabled: true
  become: true
