---
- name: "beats - download {{ item.name }} packages"
  uri:
    url: "{{ beats.download_url }}/{{ item.name }}/{{ item.name }}-{{ beats.version }}-amd64.deb"
    method: GET
    dest: "/tmp/{{ item.name }}-{{ beats.version }}-amd64.deb"
    status_code:
      - 200
      - 304

- name: "beats - install {{ item.name }} packages"
  apt:
    deb: "/tmp/{{ item.name }}-{{ beats.version }}-amd64.deb"
    state: "{{ item.package_state }}"
    update_cache: yes
  become: true

- name: "beats - copy {{ item.name }} templates"
  template:
    src: "{{ item.name }}.yml"
    dest: "/etc/{{ item.name }}/{{ item.name }}.yml"
    owner: root
    group: root
    mode: '0755'
  become: true
  notify: "main - systemctl restart {{ item.name }}"

- meta: flush_handlers

- name: "beats - ensure {{ item.name }} daemon"
  systemd:
    name: "{{ item.name }}"
    state: "{{ item.service_state }}"
    enabled: yes
  become: true
