---
- name: BEATS - include onprem tasks
  ansible.builtin.include_tasks: onprem.yml
  when: cycle_mode.name == "full" and internet_found is defined

- name: BEATS - include linode tasks
  ansible.builtin.include_tasks: linode.yml
  when: cycle_mode.name == "full" and internet_found is undefined

- name: BEATS - copy templates
  ansible.builtin.template:
    src: "{{ item.name }}.yml"
    dest: "/etc/{{ item.name }}/{{ item.name }}.yml"
    owner: root
    group: root
    mode: '0640'
  become: true
  notify: "MAIN - systemctl restart {{ item.name }}"

- name: BEATS - flush handlers
  ansible.builtin.meta: flush_handlers

- name: BEATS - ensure daemon
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    state: "{{ item.service_state }}"
    enabled: true
  become: true
