---
- name: INSTALL - download beat packages
  ansible.builtin.uri:
    url: "{{ beats.download_url }}/{{ item.name }}/{{ item.name }}-{{ lab.elastic_version }}-{{ os_distro }}.deb"
    method: GET
    dest: "/root/{{ item.name }}-{{ lab.elastic_version }}-{{ os_distro }}.deb"
    status_code:
      - 200
      - 304
  become: true

- name: INSTALL - install beat packages
  ansible.builtin.apt:
    deb: "/root/{{ item.name }}-{{ lab.elastic_version }}-{{ os_distro }}.deb"
    state: "{{ item.package_state }}"
    update_cache: true
  become: true
