---
- name: INSTALL - download beat packages
  ansible.builtin.uri:
    url: "{{ beats.download_url }}/{{ item.name }}/{{ item.name }}-{{ lab.elastic_version }}-{{ os_distro }}.deb"
    method: GET
    dest: "/var/tmp/{{ item.name }}-{{ lab.elastic_version }}-{{ os_distro }}.deb"
    owner: "{{ names.users.host.iac }}"
    group: "{{ names.users.host.iac }}"
    mode: "0640"
    status_code:
      - 200
      - 304

- name: INSTALL - install beat packages
  ansible.builtin.apt:
    deb: "/var/tmp/{{ item.name }}-{{ lab.elastic_version }}-{{ os_distro }}.deb"
    state: "{{ item.package_state }}"
    update_cache: true
  become: true
