---
- name: MAIN - fetch tfstate file
  ansible.builtin.fetch:
    src: /mnt/xcalibr/root/elysianskies/tfstate/elysianskies.json
    dest: /tfstate/elysianskies.json
    flat: true
  changed_when: false
  become: true
