---
- name: "GLUSTERFS - ensure mount path {{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  become: true

- name: "GLUSTERFS - mount volume {{ item.path }}"
  ansible.posix.mount:
    fstype: ext4
    src: "{{ item.src }}"
    opts: defaults
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  become: true
  no_log: true
