---
- name: "GLUSTERFS - ensure mount path {{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  become: true

- name: "GLUSTERFS - mount volume {{ item.path }}"
  ansible.posix.mount:
    fstype: "{{ item.fstype }}"
    src: "{{ item.src }}"
    opts: defaults
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  become: true
  no_log: true
