---
- name: MAIN - include samba tasks
  ansible.builtin.include_tasks: samba.yml
  no_log: true
  when: lan_interface.uisge is defined and item.host == ansible_hostname
  with_items:
    - "{{ mounts.samba }}"

- name: MAIN - include glusterfs tasks
  ansible.builtin.include_tasks: glusterfs.yml
  no_log: true
  when: lan_interface.uisge is defined and item.host == ansible_hostname
  with_items:
    - "{{ mounts.glusterfs }}"
