---
- name: MAIN - include samba tasks
  ansible.builtin.include_tasks: samba.yml
  no_log: true
  when: lan_ints.vlan_20 is defined and item.host == ansible_fqdn
  with_items:
    - "{{ mounts.samba }}"

- name: MAIN - include glusterfs tasks
  ansible.builtin.include_tasks: glusterfs.yml
  no_log: true
  when: lan_ints.vlan_20 is defined and item.host == ansible_fqdn
  with_items:
    - "{{ mounts.glusterfs }}"
