---
- name: "MOUNT - ensure mount path {{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

- name: "MOUNT - mount volume {{ item.path }}"
  ansible.posix.mount:
    fstype: "{{ item.fstype }}"
    src: "{{ item.src }}"
    opts: "{{ item.opts }}"
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  become: true
  no_log: true
