---
- name: MOUNT - create tvault user group
  ansible.builtin.group:
    name: tvault-users
    state: present
    gid: "{{ tvault_gid }}"
  become: true

- name: MOUNT - add user to tvault group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: tvault-users
    append: true
  become: true

- name: "MOUNT - ensure mount path {{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  become: true

- name: "MOUNT - mount volume {{ item.path }}"
  ansible.posix.mount:
    fstype: "{{ item.fstype }}"
    src: "{{ item.src }}"
    opts: "{{ item.opts }}"
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  become: true
  no_log: true
