---
- name: "SAMBA - ensure mount path {{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: "{{ names.raid_vol.group.name }}"
    mode: '0770'
  become: true

- name: "SAMBA - create credentials file {{ item.path }}"
  ansible.builtin.copy:
    content: |
      username={{ item.username }}
      password={{ item.password }}
    dest: "/root/.smb/.{{ item.username }}.smbcredentials"
    owner: root
    group: root
    mode: '0600'
  become: true
  no_log: true

- name: "SAMBA - mount volume {{ item.path }}"
  ansible.posix.mount:
    fstype: cifs
    src: "{{ item.src }}"
    opts: "credentials=/root/.smb/.{{ item.username }}.smbcredentials,{{ cifs_globals }}"
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  become: true
  no_log: true
