---
- name: "SAMBA - ensure mount path {{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.groups.tenants.name }}"
    mode: "{{ item.dir_mode }}"
  become: true

- name: "SAMBA - create credentials file {{ item.path }}"
  ansible.builtin.copy:
    content: |
      username={{ item.username }}
      password={{ item.password }}
    dest: "{{ folder_secrets_raid }}/{{ item.path.split('-')[-1] }}"
    owner: "{{ names.users.host.admin.name }}"
    group: "{{ names.users.host.admin.name }}"
    mode: "0600"
  become: true
  no_log: true

- name: "SAMBA - mount volume {{ item.path }}"
  ansible.posix.mount:
    fstype: cifs
    src: "{{ item.src }}"
    opts:
      "credentials={{ folder_secrets_raid }}/{{ item.path.split('-')[-1] }},\
      uid={{ names.users.host.admin.name }},\
      gid={{ names.groups.tenants.name }},\
      dir_mode={{ item.dir_mode }},\
      file_mode={{ item.file_mode }},\
      seal"
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  become: true
