---
- name: "SAMBA - ensure mount path {{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ names.users.host.admin }}"
    group: "{{ names.groups.raid.name }}"
    mode: "0770"
  become: true

- name: "SAMBA - create credentials file {{ item.path }}"
  ansible.builtin.copy:
    content: |
      username={{ item.username }}
      password={{ item.password }}
    dest: "{{ folder_secrets_raid }}/{{ item.path.split('-')[-1] }}"
    owner: "{{ names.users.host.admin }}"
    group: "{{ names.users.host.admin }}"
    mode: "0600"
  become: true
  no_log: true

- name: "SAMBA - mount volume {{ item.path }}"
  ansible.posix.mount:
    fstype: cifs
    src: "{{ item.src }}"
    opts:
      "credentials={{ folder_secrets_raid }}/{{ item.path.split('-')[-1] }},\
      uid={{ names.users.host.admin }},\
      gid={{ names.groups.raid.name }},\
      dir_mode=0770,\
      file_mode=0660,\
      seal,\
      vers=3.1.1"
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  become: true
  no_log: true
